### ISSUE TITLE
oathkeeper repo is too big

### ISSUE THREAD

**Issue by Lan-Phan** [ory/oathkeeper#1040]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

the first time I clone oathkeeper repo, it's too big (>1GB). Seems something's wrong in the codebase

<img width="645" alt="Screen Shot 2022-12-09 at 5 35 35 AM" src="https://user-images.githubusercontent.com/106818620/206582107-82b7229a-c842-4809-b50e-b9ae065931d2.png">

### Reproducing the bug

just clone the repo

### Version

latest code

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by Lan-Phan** [comment]
Kratos:
Receiving objects: 100% (58173/58173), 78.10 MiB | 3.94 MiB/s, done.

Oathkeeper:
Receiving objects: 100% (11380/11380), 1.25 GiB | 2.94 MiB/s, done.

**Comment by alnr** [comment]
https://github.com/ory/oathkeeper/commit/1caf42a6d8024f25cc3ae71e883ed6cd64964a89 accidentally committed (and removed) all the oathkeeper binaries. Unfortunately, we cannot remove these files from the git log without rewriting history AFAIK. You should be able to do a shallow clone for much cheaper, though: `git clone --depth=1`.

Please reopen if you know if we can get rid or compress those commits without rewriting history 👍 .
