### ISSUE TITLE
Leak sensitive secrets option not working

### ISSUE THREAD

**Issue by SkypLabs** [ory/oathkeeper#1067]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The sensitive values do not appear in the logs despite the `leak_sensitive_values` option set to true in the configuration file. Same result with the `LOG_LEAK_SENSITIVE_VALUES` environment variable.

### Reproducing the bug

1. Start an Oathkeeper instance with either the `leak_sensitive_values` configuration option or the `LOG_LEAK_SENSITIVE_VALUES` environment variable set to true.
2. Send an HTTP request comprising an `Authorization` header to the Oathkeeper instance.
3. The value of the `Authorization` HTTP header is redacted from the logs, which is not the desired behaviour.

### Relevant log output

```shell
time=2023-02-09T19:51:39Z level=info msg=Loaded config: log.leak_sensitive_values = true audience=application service_name=ORY Oathkeeper service_version=v0.40.1

...

time=2023-02-09T19:51:48Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* accept-encoding:gzip user-agent:curl/7.74.0 x-forwarded-for:172.19.0.1 x-forwarded-host:redacted.com x-forwarded-method:GET x-forwarded-port:443 x-forwarded-proto:https x-forwarded-server:c0401e6673c3 x-forwarded-uri:/redacted x-real-ip:172.19.0.1] host:api-gateway:4456 method:GET path:/redacted query:<nil> remote:172.20.0.1:44706 scheme:http] http_response=map[headers:map[authorization:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true".] size:0 status:200 text_status:OK took:20.168863ms]
```

### Relevant configuration

```yml
log:
  level: debug
  format: text
  leak_sensitive_values: true
```

### Version

0.40.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by kartoch** [comment]
I can confirm this bug with version 0.40.2.
This bug appears even if setting configuration entry `log.leak_sensitive_values = true` and/or environment variable `LOG_LEAK_SENSITIVE_VALUES=true`.

**Comment by dfeyer** [comment]
Affected to on 0.40.2, make debugging a bit more difficult

**Comment by gsmcwhirter** [comment]
Log format values also seem to not be applied (attempting to set to json myself)

**Comment by achedeuzot** [comment]
It looks like it's not taking into account the log level either 🤔 So overall the `log` config seems to be mostly ignored and using default values (?).

**Comment by achedeuzot** [comment]
You can use `LOG_LEVEL` and `LOG_FORMAT` as a temporary bypass measure.

**Comment by gsmcwhirter** [comment]
The env var method did work for level/format. Thanks.

**Comment by joshm91** [comment]
I've taken a shot at fixing this. Seems like a simple fix but I'm not quite sure how to write tests for it.

**Comment by joshm91** [comment]
The [PR](https://github.com/ory/oathkeeper/pull/1104) was merged so this issue should be solved now.

**Comment by SkypLabs** [comment]
I just tested with version 0.40.6 and it works well now. Thanks!
