### ISSUE TITLE
No response for reported security issue for a month

### ISSUE THREAD

**Issue by viters** [ory/oathkeeper#1071]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The security policy states:

> Please report (suspected) security vulnerabilities to [security@ory.sh](mailto:security@ory.sh). You will receive a response from us within 48 hours. If the issue is confirmed, we will release a patch as soon as possible depending on complexity but historically within a few days.

I have reported potential security vulnerability in Oathkeeper v0.40.1 by sending email to security@ory.sh on 18 Jan 2023 and bumped it on 23 Jan 2023 and I have not received response till today.

It would be useful to receive the response even if you do not consider my report a security vulnerability, so I could turn it into GitHub issue and someone could fix it with PR.

### Version

0.40.1

**Comment by aeneasr** [comment]
Hey @viters, sorry about that. We do get reports to security@ory.sh on a weekly basis (most of them are invalid) but we do reply within 24 hours. @vinckr can you check if @viters emails end up in Spam maybe?

Regarding the report, can you try sending me an email again to aeneas@ory.sh

**Comment by vinckr** [comment]
Hello @viters 
Apologies for that, as Aeneas pointed out above we do get a lot of spam on that address. 
But I was not able to find any incoming Email on the 18.01. or 23.01. 
Also nothing from viters or the email listed in your gh profile @viters.
If the messages ended up in spam - which seems the only reasonable explanation by now - they are deleted by now.... 
Please also include me in the report vincent@ory.sh and feel free to let us know here when you sent it,
thanks 🙏

**Comment by viters** [comment]
@aeneasr @vinckr 
Thanks for response! That was my thought, but I could not find other way to reach you rather than GitHub issue.
![image](https://user-images.githubusercontent.com/13100466/221804046-bd5d6890-bd94-406a-b54a-fb5548337e95.png)
This is the summary from Gmail (in polish, sorry I did not quickly find lang switch) to confirm that it looked right from my side.

Thanks for direct contact to you! I will resend the email.

**Comment by vinckr** [comment]
> Maybe it is because email contains code, screens and some text that could be marked as malicious and was blocked?

Hard to say bc the original email was deleted, but we received the new one without any problems... 
Thanks for reaching out and working to make Ory more secure 🙏
