### ISSUE TITLE
Observed memory leak in v0.40.3

### ISSUE THREAD

**Issue by shoujun** [ory/oathkeeper#1112]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When upgrading from v0.38.14 to v0.40.3, we observed memory leak on our Oathkeeper instances, and we have to revert the upgrade.

![SCR-20230616-irdc](https://github.com/ory/oathkeeper/assets/21117823/9c71df5d-fc2d-4a47-964e-e2e5191498ce)

![SCR-20230616-iuii](https://github.com/ory/oathkeeper/assets/21117823/cd5731b7-08bb-4825-bdc3-7bd6267f6364)

### Reproducing the bug

Need the instructions to reproduce the issue out of our PROD ENV.

### Version

v0.40.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

**Comment by z0lope0z** [comment]
is the fix part of v0.40.4 release?

https://github.com/ory/oathkeeper/releases/tag/v0.40.4

**Comment by aeneasr** [comment]
I believe so!

**Comment by alnr** [comment]
Resolved in 0.40.4
