### ISSUE TITLE
Add WWW-Authenticate Header on 401

### ISSUE THREAD

**Issue by JohnCMcDonough** [ory/oathkeeper#119]
Is there any way we can add the WWW-Authenticate header to a 401 response so that a user using a web browser will be prompted for credentials?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication

**Comment by aeneasr** [comment]
I see, maybe we could add a configuration setting to enable this for the client_credentials authorizer to enable this. Whalt do you think?

**Comment by JohnCMcDonough** [comment]
That sounds good!

**Comment by JohnCMcDonough** [comment]
I've never written anything in Go, but I'll give it a shot!

**Comment by ngrigoriev** [comment]
I actually have a better idea. Currently there is a mutator that adds the headers. This mutator is applied only in case of a positive response. I would probably create two mutators instead - one for positive response and one for negative. And I would extend the list of values available for the template to include some request-specific ones (host, path, maybe original request headers etc). This would cover a bunch of additional use cases without breaking the concept of being the authorizer for APIs.

**Comment by aeneasr** [comment]
That's a good idea! We wanted to have a "deny" strategy but we were not completely sure how to approcha this. Maybe splitting mutators into allow/deny is the way to go!
