### ISSUE TITLE
Configuration reference isn't displayed at ory.sh

### ISSUE THREAD

**Issue by renom** [ory/oathkeeper#1190]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

https://www.ory.sh/docs/oathkeeper/reference/configuration
The configuration block is empty:
![image](https://github.com/user-attachments/assets/528d35ff-a82a-4baf-baaf-0275d9a3ddb4)

### Reproducing the bug

Open https://www.ory.sh/docs/oathkeeper/reference/configuration

### Version

-

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by alnr** [comment]
Fixed!
