### ISSUE TITLE
Inconsistent Environment Variable Docs

### ISSUE THREAD

**Issue by bensont1** [ory/oathkeeper#121]
For consistency, should be HTTP_TLS_CERT_PATH and HTTP_TLS_KEY_PATH

`certString, keyString := viper.GetString("HTTP_TLS_CERT"), viper.GetString("HTTP_TLS_KEY")
	certPath, keyPath := viper.GetString("HTTP_TLS_CERT_PATH"), viper.GetString("HTTP_TLS_KEY_PATH")`

https://github.com/ory/oathkeeper/blob/26fdda126a9b322e5310a2a3a3ed83949f640d2c/cmd/helper_messages.go#L179

**Comment by aeneasr** [comment]
Oh, it's `HTTP` and `HTTPS`, thanks!

**Comment by bensont1** [comment]
@aeneasr Sorry I should have been more clear, the docs in `helper_messages.go` shows the Environment variable as `HTTPS_TLS_CERT_PATH` but the code uses  `HTTP_TLS_CERT_PATH`. Since I was looking at only the docs initially, took me a little while to figure out why it wasn't using the certs. Just wanted to make sure other people who look at the docs don't go in a circle figuring it out :)

**Comment by fredbi** [comment]
To be consistent with hydra, I am going to move them all to HTTPS.
I let live the same inconsistent setup in keto.
ok to make this  all `HTTTPS_xxx`  like with hydra?

**Comment by bensont1** [comment]
Yeah  it should be HTTPS, maybe only two T’s :)

On Oct 11, 2018, at 12:20 AM, fredbi <notifications@github.com<mailto:notifications@github.com>> wrote:


To be consistent with hydra, I am going to move them all to HTTPS.
I let live the same inconsistent setup in keto.
ok to make this all HTTTPS_xxx like with hydra?
