### ISSUE TITLE
Missing serve all, both proxy/api using 4455

### ISSUE THREAD

**Issue by seglberg** [ory/oathkeeper#122]
It appears that Oathkeeper is missing a `serve all` command similar to Hydra. This would be useful for launching both in a single container.

Likewise, both the `serve proxy` and `serve api` commands bind to port 4455, even though the help documentation states the api will bind to port 4456 by default.

**Comment by bensont1** [comment]
I think it was intended this way because the proxy is meant to be public facing routing, while the API is the management portion of oathkeeper.

**Comment by seglberg** [comment]
Absolutely!

It just makes it easier to deploy into K8S if we can run both in the same container. Currently we have to define two separate containers in our pod (which works just fine). It'd just be a "nice to have" if we could run both at the same time and have the proxy run on 4455 and api run on 4456.

**Comment by aeneasr** [comment]
Yeah this could be added at some point, tracking as enhancement!
