### ISSUE TITLE
Keto Warden Authorizer: Make Subject configurable.

### ISSUE THREAD

**Issue by lsjostro** [ory/oathkeeper#128]
**Is your feature request related to a problem? Please describe.**
Make Subject configurable instead of hard coding to `session.Subject`
https://github.com/lsjostro/oathkeeper/blob/master/proxy/authorizer_keto_warden.go#L96

**Describe the solution you'd like**
Would be nice to be able to pass something from the Extra attribute. i.e `session.Extra["email"]`, as Subject to Keto. Maybe use the same implementation as in `headers` in Credentials Issuers using go templates?

**Comment by aeneasr** [comment]
Yeah that makes sense I guess!

**Comment by lsjostro** [comment]
cool! I'll propose a PR.
