### ISSUE TITLE
Implement GRPC response handler in Decisions API

### ISSUE THREAD

**Issue by lsjostro** [ory/oathkeeper#134]
**Is your feature request related to a problem? Please describe.**]

Implement GRPC response in the Decisions API. If Content-type is `application/grpc` ORY Oathkeeper should response with the appropriate GRPC response.

**Describe the solution you'd like**

Something like this in the judge handler:

```golang
func grpcHandlerFunc(rpcServer *rpc.Server, other http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        ct := r.Header.Get("Content-Type")
        if r.ProtoMajor == 2 && strings.Contains(ct, "application/grpc") {
            rpcServer.ServeHTTP(w, r)
        } else {
            other.ServeHTTP(w, r)
        }
    })
}
```

**Comment by aeneasr** [comment]
Would it be possible to give more context on this? I've never used grpc myself, so I lack some background. Is grpc running over HTTP(s)? Are the same headers used and do they represent the same things? If grpc runs as a (binary) format over HTTP, why do we even care here? We're not transforming/modifying the payload, right?

**Comment by lsjostro** [comment]
Yes gRPC runs over HTTP/2. The headers are more or less the same as in HTTP/1 /w Authorization headers etc (read more here https://apievangelist.com/2018/02/05/headers-used-for-grpc-over-http2/). But gRPC have some addtitional headers as well. gRPC client except "binary" payload back, whenever a json payload is returned it will not be recognized but the grpc client, like a auth failure from oathkeeper. 

Empty body response would be fine but with the grpc-status and grpc-message header with the error. 

But your are totally right whenever the request is `granted` by oathkeeper everything works as excepted.
This fix would make the gRPC client act accordingly if we get a auth failure for instance.

**Comment by aeneasr** [comment]
Ok, I think this requires a bit more thinking around gRPC in general:

1. Do we provide gRPC APIs alongside REST ones?
2. How do we document, generate, and publish gRPC APIs?
3. What security mechanisms of gRPC (if any) can we use or enhance?

I think this will be a longer discussion, but it will be a good one!

**Comment by lsjostro** [comment]
A quick fix which works sufficient is to do something like this:
![image](https://user-images.githubusercontent.com/500754/47996932-7f7acc00-e0fa-11e8-9cc1-5a1be0a68759.png)

from previously getting this reponse:
`rpc error: code = Internal desc = transport: received the unexpected content-type "application/json"`
and now getting:
`rpc error: code = Unauthenticated desc = Unauthorized`

**Comment by lsjostro** [comment]
probably would be enough to implement the content type in https://github.com/ory/herodot

this workaround is ok for me now.
![image](https://user-images.githubusercontent.com/500754/47999054-8f49de80-e101-11e8-933f-bacf01beffd2.png)

**Comment by aeneasr** [comment]
Yeah, I think it makes sense to have the workaround in oathkeeper directly. We'll need a bit more work on herodot to support grpc properly. Feel free to PR!

**Comment by rverma-jm** [comment]
Looks like this issue still prevails. Any workaround in 2020?

**Comment by aeneasr** [comment]
PRs and contributions are always welcome, so if you want to give this a shot @rverma-jm

**Comment by namsoila** [comment]
@lsjostro Are you please able to indicate where you would add this work around currently within the current release?

Would it be here:

https://github.com/ory/oathkeeper/blob/master/api/decision.go#L86

And would you completely replace the current function?

Thanks.

**Comment by hypnoglow** [comment]
We are also interested in this feature.

Is there any progress on this? If not, is there anything we still need to discuss before changes can be made? 

I could look into this and try to contribute this feature, if there are no blockers.

**Comment by aeneasr** [comment]
Thank you, we are currently implementing GRPC in Ory Keto and plan to do the same in Ory Oathkeeper once we habe the build and toolchain figured out! If you want check over to github.com/ory/keto for issues on GRPC or reach out to @zepatrik / Patrik (ory) on Slack

**Comment by aeneasr** [comment]
Incorrect stalebot detection - this was assigned a milestone.

**Comment by meysam81** [comment]
This is still an issue in 2024
