### ISSUE TITLE
make id_token credential issuer optional

### ISSUE THREAD

**Issue by stszap** [ory/oathkeeper#136]
Currently users have to specify a random hs256 secret for oathkeeper even if they don't use id_token credential issuer. I think it would be more convenient to atomatically disable this issuer if there are no configurations for it.

Steps to reproduce:
```
$ docker run --rm -it -e DATABASE_URL=memory oryd/oathkeeper:v1.0.0-beta.9 serve api
FATA[0000] Unable to initialize the ID Token signing algorithm  error="The secret set in CREDENTIALS_ISSUER_ID_TOKEN_HS256_SECRET must be 32 characters long."
```

**Comment by aeneasr** [comment]
Yeah that makes sense - so should the default be to just not transform the credentials at all (noop)?

**Comment by stszap** [comment]
Yes, I think "noop" as the default option makes the most sense.

**Comment by aeneasr** [comment]
Sounds good!
