### ISSUE TITLE
Update README building-from-source part with the gomodule way

### ISSUE THREAD

**Issue by pink-lucifer** [ory/oathkeeper#149]
As latest release have already been migrated to go module, the dep doesn't work any more, it would be better to update the instructions same as keto or hydra does, or add up additional note to clarify.

[README - building-from-source](https://github.com/ory/oathkeeper#building-from-source)

[hydra - README - buiding from source](https://github.com/ory/hydra#building-from-source)

**Comment by aeneasr** [comment]
Nice catch! Would you mind creating a PR?

**Comment by pink-lucifer** [comment]
@aeneasr 
I apologize that i didn't follow up on this response timely, is this taken care of?
It would be my pleasure to work on this PR.
