### ISSUE TITLE
Unable to install oathkeeper CLI

### ISSUE THREAD

**Issue by ngrigoriev** [ory/oathkeeper#161]
**Describe the bug**
Unable to install oathkeeper CLI

**To Reproduce**
1. Run `$ go get github.com/ory/oathkeeper`

```
# github.com/ory/x/metricsx
../../../go/src/github.com/ory/x/metricsx/middleware.go:101:10: undefined: analytics.Config`
```

**Comment by aeneasr** [comment]
Please use the installation instructions, they are in the readme: https://github.com/ory/oathkeeper#building-from-source
