### ISSUE TITLE
Support alternate matching strategy for API routes

### ISSUE THREAD

**Issue by aeneasr** [ory/oathkeeper#167]
Right now only regex-based matching is supported. In the future we should also support glob and others.

**Comment by aeneasr** [comment]
https://github.com/gobwas/glob

**Comment by aeneasr** [comment]
https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPMatchRequest

**Comment by aeneasr** [comment]
This is now implemented

**Comment by cameron-martin** [comment]
Is there any information available on how this feature is used?
