### ISSUE TITLE
Trusting self-signed certificates

### ISSUE THREAD

**Issue by jboalml** [ory/oathkeeper#181]
I am trying to connect to a resource server using Oathkeeper in Docker for Windows and, since I am still in my development setup, I am using self-signed certificates. So far, I have successfully managed to hit the resource server, but Oathkeeper keeps complaining about the server certificate being signed by an unknown authority. The log message is the following:

```
time="2019-04-18T15:43:38Z" level=warning msg="Access request denied because roundtrip failed" error="x509: certificate signed by unknown authority" granted=false
2019/04/18 15:43:38 http: proxy error: x509: certificate signed by unknown authority
```

It would be useful to support using self-signed certificates in Oathkeeper to allow testing HTTPS connections before going into production. I suggest two options:
* Incorporate a flag to disable resource server certificate verification, just like ``--skip-tls-verify`` in Hydra. However, this should not affect incoming TLS connections.
* Being able to feed the certificate chain to perform validation.

I believe both alternatives have different use cases. The first one would allow to quickly test HTTPS communication with resource servers, whereas the second would be useful to secure last mile connections in those scenarios where you cannot or do not want to use certificates signed by a CA.

Any help would be greatly appreciated.

P.S. This an extended repost of the following [forum message](https://community.ory.sh/t/trusting-self-signed-certificate-in-development/1081) suggested by @arekkas.

**Comment by aeneasr** [comment]
Just to get it right - you want the connectivity to the upstream server to be encrypted in transport (HTTP over TLS) with self-signed certificate which fails because of CA verification?

**Comment by jboalml** [comment]
> Just to get it right - you want the connectivity to the upstream server to be encrypted in transport (HTTP over TLS) with self-signed certificate which fails because of CA verification?

Yes, this is exactly the problem. My development resource server does not have a public domain name and therefore I cannot use a certificate signed by a CA. The only solution I have found so far is to secure Oathkeeper's incoming requests and change my upstream redirection to HTTP.

**Comment by aeneasr** [comment]
Sorry for the late reply, sounds like a reasonable feature request. Open to accept PRs!

**Comment by wraix** [comment]
I have created a function that should do what is required, but im having trouble figuring out how to implement the configuration part. Help would be appreciated. - At least this shows how to implement extending the Root CA for upstream connections.

This is not ready to be merged. I just did not understand how pull requests work on forks. Is my first time, sorry.

**Comment by Zero-2** [comment]
Any news about this?

**Comment by wraix** [comment]
Yes i have completed the code that does the heavy lifting, hope it will be satisfactory.

What seems to be missing according to the contribution guidelines are test case, documentation and maybe some code formatting?

**Comment by wraix** [comment]
The feature should be completed in PR [706](https://github.com/ory/oathkeeper/pull/706)

**Comment by ReeganExE** [comment]
Hi team, how about `authenticators`? Does `oathkeeper` currently support TLS with self-signed cert? I believe TLS is being used everywhere even internal communication nowadays.

```yml
authenticators:
  cookie_session:
    enabled: true
    config:
      check_session_url: https://kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
```

**Comment by aeneasr** [comment]
Not yet, I think support for custom CAs should be something for Oathkeeper next (#441)! I think the easiest workaround for now is to register the certificate in the trust store of the OS / container?
