### ISSUE TITLE
json: cannot unmarshal string into Go value

### ISSUE THREAD

**Issue by flasaracina** [ory/oathkeeper#183]
Hello, whenever I request a resource via oathkeeper I receive this error:

json: cannot unmarshal string into Go value of type proxy.AuthorizerKetoWardenConfiguration

I am using the lastest version of oathkeeper (v0.15.1) with docker and I think it is somewhat related to #182 

There is a way for me to resolve the issue or I should wait for a bugfix?
Thanks

**Comment by MikitaKurlovich** [comment]
The same issue.

**Comment by aeneasr** [comment]
Is this resolved with v0.15.2 ?

**Comment by flasaracina** [comment]
@aeneasr Yes! It all works now, thanks
