### ISSUE TITLE
Url matching should be available in authenticators

### ISSUE THREAD

**Issue by flasaracina** [ory/oathkeeper#205]
Feature Request

As of today when defining an oathkeeper policy we can declare a rule based on a regular expression like so:

```json
{
      "id":"rules:one",
      "upstream":{
         "url":"http://upstream-sample-server/"
      },
      "match":{
         "url":"http://oathkeeper-proxy/<.*>/foo/<.*>",
         "methods":[
            "GET"
         ]
      }
...
}
```
and reference that regex's matches later in the `authorizer` section:

```json
{
      ...
      "authorizer":{
         "handler":"keto_engine_acp_ory",
         "config":{
            "required_resource":"resource:$1:foo:$2",
            "required_action":"action:foo:read",
            "flavor":"glob"
         }
      }
}
```
I'd like to have the opportunity to reference those matches also in the `authenticators` section. 
Since oauth scopes are not for authorization, but just for, well, scoping the access to some resources, it would be useful to define a rule with a dynamic scope. Think about a multi-tenant system where we have two tenants with the following endpoints:

`https://tenant-1.my-api.com/whatever`
`https://tenant-2.my-api.com/whatever`

they would proxy to oathkeeper and thus behind the scenes, they become:

`https://oathkeeper/tenant-1/whatever`
`https://oathkeeper/tenant-2/whatever`

Internally, having the tenant in the URL is useful because I could then write a policy that could use a regular expression to require a tenant-dependent scope in the authn phase.

This way I'll have a much cleaner separation between authn and authz and a much more cleaner keto rules (tenant independent)

In fact, scopes are not for authorization, so it makes sense to create tenant specific clients that have a tenant specific scope. Resources and action are therefore tenant agnostic, reducing the number of policy per API and a much more manageable system overall.

Ex:
```yaml
tenant A:
  scopes:
    - tenant.a
    - api-1.foo

tenant B:
  scopes:
    - tenant.b
    - api-1.foo


tenant G:
  scopes:
    - tenant.*
    - api-1.foo
```

Tenant A and B can access resources under `api1-foo` scope (under some authz restrictions that are different per client not shown here because scopes are not meant for authorization) AND only data related to their own tenant. 

Tenant G on the other hand can access that api and could ask data for any tenant given the right authorization privileges.

It makes sense?
Sorry for my bad english

**Comment by aeneasr** [comment]
Sorry for the late reply, I think it generally makes sense to support that. However, we want to improve the way this works anyways, using for example Go Templates. This will however take a bit of time...

**Comment by flasaracina** [comment]
thank you for the reply. I'll keep an eye on the updates then. 

Keep up the good work, guys

**Comment by aeneasr** [comment]
This is now implemented!

**Comment by kinloth** [comment]
> This is now implemented!

Hi, could you please explain how to make it work?
I tried either using Go Templates:
`[{
    "match": {
        "url": "http://oathkeeper/v2/action/<.*>",
        "methods": [
            "POST"
        ]
    },
    "authenticators": [{
        "handler": "oauth2_introspection",
        "config": {
            "required_scope": ["{{ printIndex .MatchContext.RegexpCaptureGroups 0 }}"],
            "scope_strategy": "exact"
        }
    }]
}]`
either by variables, like in keto_engine_acp_ory:
`"match": {
        "url": "http://oathkeeper/v2/action/<.*>",
        "methods": [
            "POST"
        ]
    },
    "authenticators": [{
        "handler": "oauth2_introspection",
        "config": {
            "required_scope": ["$2"],
            "scope_strategy": "exact"
        }
    }]`

and many other variations with no success...

**Comment by aeneasr** [comment]
Could you please open a new issue and fill out the issue template? That way I will be able to help
