### ISSUE TITLE
config file is ignored if the file extension is anything but yml or non-existent

### ISSUE THREAD

**Issue by Sahasrara** [ory/oathkeeper#206]
**Describe the bug**
Whether you specify the config file with `--config` or put a config file in the home directory named .oathkeeper.yaml, the configuration is ignored if the file provided does not use the exact extension `.yml`.

Further, if you provide a bogus --config file string, oathkeeper startup as if nothing has gone wrong

**Reproducing the bug**

1. Install oathkeeper
2. Attempt to start it with the --config option providing any file other than one ending in .yml
3. Notice the config file is ignored.

**Expected behavior**

I'd expect the .yaml extension to work, and I'd expect to receive an error if I provide bad input for the --config option.

**Environment**

- Version: v1.16
- Environment: OSX, Ubuntu 16.04

**Comment by aeneasr** [comment]
Thank you, would you be up for a PR?

**Comment by aeneasr** [comment]
This will be resolved once we move this project to Koanf which is standard for all of our other OSS products! Therefore, closing this as it is a wontfix/upstream
