### ISSUE TITLE
Url matching http method should be available in authenticators

### ISSUE THREAD

**Issue by LarryMai** [ory/oathkeeper#221]
Feature Request

I have a policy like below

```
{
    "id": "rules:resource-server-oathkeeper-animals-11",
    "upstream": {
      "url": "http://192.168.255.152:4478",
      "strip_path":"/api/v1"
    },
    "match": {
      "url": "http://192.168.255.152:4455/api/v1/cats/<[^/]+>/<[^/]+>",
      "methods": [
        "POST",
        "GET",
        "PUT",
        "DELETE"
      ]
    },
    "authenticators": [
      {
              "handler": "jwt",
              "config": {
                "trusted_issuers":
                [
                  "http://localhost:4444/",
                  "http://localhost:4456/",
                  "http://oathkeeper-api:4456"
                ]
              }
      } 
    ],
    "authorizer": {
      "handler": "keto_engine_acp_ory",
      "config": {
        "required_action":"actions:$2",
        "required_resource": "resources:cats:$1",
        "flavor": "regex"
      }
    },
    "credentials_issuer": {
            "handler": "id_token",
            "config":{
                "aud": ["example-auth-code","consumer-app", "test-client"]
            }
        }
```
In the match section,  our format of the match url is :  
http://192.168.255.152:4455/api/v1/cats/<cat_id>/<action_id>
methods : [ POST, PUT, DELETE, GET].
where cat_id , action_id represented by regex.
  
Is any way that keto_engine_acp_ory authorizer can see the HTTP method of matching URL  when the request is authenticated or Oathkeeper can implement such feature? 
It makes sense if I don't have custom actions in my back-end service and directly use HTTP method as keto-policy's action. 

Sorry for my bad english.

**Comment by aeneasr** [comment]
Yes absolutely! We also want to improve this process with Go Templates!

**Comment by everas7** [comment]
Is there any update on this issue?

**Comment by aeneasr** [comment]
Contributions welcome

**Comment by aeneasr** [comment]
Incorrect stalebot detection - this was assigned a milestone.
