### ISSUE TITLE
Add ability to modify responses. 

### ISSUE THREAD

**Issue by tabeth** [ory/oathkeeper#223]
**Is your feature request related to a problem? Please describe.**
With the ability to proxy requests, sometimes the proxied request will include headers you won't necessarily want to be included in the response. The ability to delete or modify these headers would be helpful for both a security perspective and user friendliness (cleaning up an api via oathkeeper). 

**Describe the solution you'd like**
Something similar to mutators where you can specify key and values for headers that be inserted into the response. 

**Describe alternatives you've considered**
You can do this currently with Kong and HAProxy (there may be more as well).

**Comment by aeneasr** [comment]
This sounds sensible! We definitely want to remove the e.g. Cookie headers or Authorization headers in some cases! Happy to accept PRs

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
