### ISSUE TITLE
mTLS + SPIFFE

### ISSUE THREAD

**Issue by dustin-decker** [ory/oathkeeper#247]
**Is your feature request related to a problem? Please describe.**

It would be nice to have the option to use mTLS to the gateway and derive the identity from the client's certificate as an alternative or supplement to Oauth2 and OIDC. A specification for mTLS identity that has been gaining traction is SPIFFE, which has a growing amount of issuers and consumers: https://spiffe.io/

**Describe the solution you'd like**

- Derivation of identity from X.509 SPIFFE Verifiable Identity Document (SVID): https://github.com/spiffe/spiffe/blob/master/standards/X509-SVID.md
- X.509 client certificate validation from a given CertPool

**Describe alternatives you've considered**

In SPIFFE, the identity is defined with the SPIFFE ID which is contained as a single SAN on the certificate. A common alternative for mTLS identity is using the other PKIX Relative Distinguished Names (RDNs) https://golang.org/pkg/crypto/x509/pkix/#Name

**Additional context**

I might be able to implement this if the proposal fits well with this project.

**Comment by aeneasr** [comment]
Absolutely agree!

**Comment by aeneasr** [comment]
And it would be greatly appreciated if you could contribute this :)

**Comment by aeneasr** [comment]
Thank you for originally opening this issue. Unfortunately, it does not appear that there is public interest in the issue. Given the complexity and lack of involvement from the community I will be closing this issue to free up the backlog.

If new appetite for this comes up feel free to discuss or reopen or create a new issue! ☺️ :octocat: 

If we at Ory end up with a use case that requires this, we'll put it back on the roadmap also!
