### ISSUE TITLE
Mutator: unrecognized by oathkeeper (v0.17.5)

### ISSUE THREAD

**Issue by stanleyyuenyiu** [ory/oathkeeper#248]
in terms of Docker version

Mutator only work at v0.17.0-beta1, but not latest or v0.17.5

so v0.17.0-beta1 is newer than v0.17.5?? What the hack of this version logic?

**Comment by aeneasr** [comment]
0.17.5 accidentally includes a patch that changes mutator behavior to be able to support multiple mutators. It should have been released as 0.18.0. 0.17.5 will be un-released and re-released as 0.18.0

In the future, please use appropriate language and consider a friendlier tone as mandated by our contributing guidelines. This is an open source project after all.

**Comment by aeneasr** [comment]
This issue has been resolved.

**Comment by stanleyyuenyiu** [comment]
Understood, Please forgive me and my un-friendly tone
