### ISSUE TITLE
Support automatic reloading and rotating of JWKs Keys

### ISSUE THREAD

**Issue by aeneasr** [ory/oathkeeper#253]
We would like to reload and rotate JWKs for signing ID Tokens.

This could work on e.g. Kubernetes by using `oathkeeper credentials generate` and updating the kubernetes secret. To achieve that we need:

- [ ] To update the helm chart to support a cron job which is capable of updating the k8s secret with a new jwks key
- [ ] To allow the oathkeeper cli to append keys to an existing jwks file
- [ ] To enable hot reloading for jwks keys

/cc @piotrmsc

**Comment by piotrmsc** [comment]
Yeah 🎉 
- Additionally we could make this cron job optional via helm override
- Cron job as a golang? wrapper for cli storing created certs in k8s secrets
- Mount defined secret as a volume in oathkeeper chart
