### ISSUE TITLE
Update mutators in documentation

### ISSUE THREAD

**Issue by MichielVanderlee** [ory/oathkeeper#261]
In the documentation for access rules, the `mutator` field is singular and an object. However, the code expects `mutators` with an array of objects as value. 

Bonus issue: 
Error message is only clear when using a json rules file, not when using yaml.
json error:
`error="json: unknown field \"mutator\""`

yaml error:
`error="An internal server error occurred, please contact the system administrator"`

**Comment by aeneasr** [comment]
Would you be open to fix that in a PR? :)

**Comment by MichielVanderlee** [comment]
I don't have much time atm.

Might I suggest versioned documentation? 
I realize that it's still v0 and open source, but it'd be great documentation could at least be marked 'up to date with version x' or something like that. 
Yesterday I spend quite a bit of time trying to get `/judge` to work only to find that it's now `/decisions`. That documentation has been update just today.

**Comment by aeneasr** [comment]
Because the documentation covers multiple projects this is not straight forward but you can find how versioning works here:

https://www.ory.sh/docs/ecosystem/versioning

**Comment by MichielVanderlee** [comment]
Ah, thank you!

**Comment by aeneasr** [comment]
I'm closing this - I'd however like to inform you that we'll be adding versioning to access rules to improve the upgrade experience: #266
