### ISSUE TITLE
Access-rules conversion error.

### ISSUE THREAD

**Issue by ggimes** [ory/oathkeeper#274]
Hi there, I'm having an issue with the oathkeeper access rules I defined. For testing purpose, I tried to set the content of `access-rules.json` with the example from the documentation [here](https://www.ory.sh/docs/oathkeeper/pipeline/authn#access-rule-example) and get a similar output. Here's how I install oathkeeper: 

```
helm install --set 'image.tag=v0.19.1' -f config.yaml --set-file 'oathkeeper.mutatorIdTokenJWKs=./jwks.json' --set-file 'oathkeeper.accessRules=./access-rules.json' --namespace oathkeeper ory/oathkeeper
```

and the command output:

```
Error: YAML parse error on oathkeeper/templates/configmap-rules.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key
```

If `access.rules.json` content is set to `[]` the installation succeeds.

If I run
```
helm install --dry-run --set 'image.tag=v0.19.1' -f config.yaml --set-file 'oathkeeper.mutatorIdTokenJWKs=./jwks.json' --set-file 'oathkeeper.accessRules=./access-rules.json' --namespace oathkeeper ory/oathkeeper
```

I get:

```
...
apiVersion: v1
kind: ConfigMap
metadata:
  name: broken-jellyfish-oathkeeper-rules
  namespace: oathkeeper
  labels:
    app.kubernetes.io/name: oathkeeper
    helm.sh/chart: oathkeeper-0.0.24
    app.kubernetes.io/instance: broken-jellyfish
    app.kubernetes.io/version: "v0.16.0-beta.4_oryOS.12"
    app.kubernetes.io/managed-by: Tiller
data:
  "access-rules.json": |
    [{
  "id": "some-id",
  "upstream": {
    "url": "http://my-backend-service"
  },
  "match": {
    "url": "http://my-app/some-route",
    "methods": [
      "GET"
    ]
  },
  "authenticators": [{
    "handler": "noop"
  }]
}]
...
```

The JSON format isn't converted properly... Hmm. Any idea / suggestion is welcome :-) (FYI I just started working with k8s and helm)

Thanks.

**Comment by ggimes** [comment]
Ok I think I found the potential issue. In the Helm file: `templates/configmap-rules.yaml`, if I changed the line
```  {{ .Values.oathkeeper.accessRules | default "[]" }}``` to ```{{ .Values.oathkeeper.accessRules | default "[]" | indent 4}}```. The json format seems correct and the installation succeeds.

**Comment by aeneasr** [comment]
Sorry for the late reply. I will investigate this now!
