### ISSUE TITLE
missing release assets in release v0.19.2-beta.1+oryOS.12

### ISSUE THREAD

**Issue by adamplansky** [ory/oathkeeper#275]
**Describe the bug**

 release assets is missing in latest release v0.19.2-beta.1+oryOS.12. This results in failing install.sh

**Reproducing the bug**

```bash
1. curl https://raw.githubusercontent.com/ory/oathkeeper/master/install.sh | bash -s -- -b .
2. ./oathkeeper help
bash: ./oathkeeper: No such file or directory
```

- Version: v0.19.2-beta.1
- Environment: Ubuntu

**Comment by aeneasr** [comment]
Thanks, I re-released it as beta.2
