### ISSUE TITLE
Call an external service to enrich the internal session state

### ISSUE THREAD

**Issue by Sbou** [ory/oathkeeper#277]
**Is your feature request related to a problem? Please describe.**

In the Oathkeeper decision engine, it's not possible to call an external service to add context in the request sent to Keto.

**Describe the solution you'd like**

We have the ability to do that at the **mutator** step with "hydradator" but not before the **authorizer** step.
Following the XACML definition, I would like to call a PIP service from the PEP (Oathkeeper) or the PDP (Keto) services.

![XACML definition](https://www.axiomatics.com/wp-content/uploads/2017/11/xacml_architecture.png)

**Describe alternatives you've considered**

At the moment, I have to call this external service before to call Oathkeeper and add the context in the url of the access rule.

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
