### ISSUE TITLE
[Helm chart] Quick changes

### ISSUE THREAD

**Issue by ggimes** [ory/oathkeeper#278]
**Is your feature request related to a problem? Please describe.**

I noticed that having `istio-injection` enabled was preventing Kubelet liveness/readiness probes to reach oathkeeper API port.

**Describe the solution you'd like**

In order to solve it, I need to either remove the api port from the Pod definition or add an annotation in the Pod resource (https://istio.io/docs/ops/app-health-check/#use-annotations-on-pod). For this second and better option, the Deployment template needs to be updated (see below). There are some other minor changes as well.

- `helm/oathkeeper/Chart.yaml` (Update: Line 22)
```
<<< version: 0.0.24
>>> version: 0.0.28
```

- `helm/oathkeeper/templates/deployment.yaml` (Add: Line 11)
```Line 11
  labels:
{{ include "oathkeeper.labels" . | indent 4 }}
# Add the posssibility to add Annnotations to the Pod resource. 
# Needed for Istio for instance:
# https://istio.io/docs/ops/app-health-check/#use-annotations-on-pod
>>>  {{- with .Values.deployment.annotations }}
>>>  annotations:
>>>    {{- toYaml . | nindent 4 }}
>>>  {{- end }}
```

I also noticed that the demo mode doesn't work anymore because the `access-rules` definitions from https://raw.githubusercontent.com/ory/k8s/master/helm/charts/oathkeeper/demo/access-rules.json is outdated (`mutator` -> `mutators`)

Thanks

**Comment by aeneasr** [comment]
Feel free to shoot up a PR :)

**Comment by aeneasr** [comment]
Merged :)
