### ISSUE TITLE
Use another Policy server than Keto

### ISSUE THREAD

**Issue by Sbou** [ory/oathkeeper#288]
I would like to use another Polcy server than Keto to be able to use an existing server or a server which implements a model not supported by Keto.

**Describe the solution you'd like**

Even if I can set an URL to target a server, this one has to match the Keto endpoint for the input and output.
It would be better if I can customise the endpoint settiings.

**Describe alternatives you've considered**

I implement a service with the same signature than Keto to be able to call my other policy engine.

**Comment by aeneasr** [comment]
Which one specifically? Also, this is a dupe of https://github.com/ory/oathkeeper/issues/201

**Comment by Sbou** [comment]
I wrote my own service  by using [Casbin](https://casbin.org/docs/en/overview) library.

**Comment by aeneasr** [comment]
I see, in that case this is definitely something we want to solve with #201 . Would you be open to contribute that handler? If so, we could discuss architecture/implementation details and testing in #201 !

**Comment by aeneasr** [comment]
There is now a `remote_json` handler for authorization!
