### ISSUE TITLE
Missing Content-type

### ISSUE THREAD

**Issue by Sbou** [ory/oathkeeper#289]
**Describe the bug**

I implemented a service which match with the Keto signature to use another Policy server.
But Oathkeeper doesn't set the Content-type = application/json when it calls Keto.

The technology that I use follow a strict rule about the body received.
If it's a json body then the content-type must be **application/json**.

Is it possible to add this header in your request ?

Thanks

**Comment by aeneasr** [comment]
Tracked as a bug

**Comment by aeneasr** [comment]
And feel free to PR this!
