### ISSUE TITLE
Generalize the use of values extracted from the rule

### ISSUE THREAD

**Issue by Sbou** [ory/oathkeeper#292]
**Is your feature request related to a problem? Please describe.**

We can only use the values extracted from the regex match rule in the Keto authorizer.
It could be interessting to have access to this values in other authorizers or mutators.

**Describe the solution you'd like**

The Hydrator only receives the **AuthenticationSession**, so either we can send additional paramters either the extracted values are stored to the **AuthenticationSession** to be able to use everywhere.

**Additional context**

If it was in the Session we can use this values in custom claims (token_id mutator) as well.

**Comment by Sbou** [comment]
Any advice to use it ?

**Comment by aeneasr** [comment]
Sorry for missing this. This makes sense, triaging as an enhancement.

**Comment by Sbou** [comment]
I will try to add this functionality.

Here is what I propose to do.

Currently the **AuthenticationSession** is created by the authenticator. I think, it could be great to have a **session object** for the life of the request handler.

Each steps could enrich or use the values in this session.

For that, I think to modify the _Authenticator_ interface like this:

```go
Authenticate(r *http.Request, config json.RawMessage, rule pipeline.Rule) (*AuthenticationSession, error)
```
To

```go
Authenticate(r *http.Request, session *AuthenticationSession, config json.RawMessage, rule pipeline.Rule) error
```

I have to update all the authenticators to match this signature.

About the **AuthenticationSession** structure, I can either add a **RuleValues [] string** field or add an array in Extra.

What do you think ?

I must also update the Hydrator to take into account this change of signature.

And last point about compatibility, do I keep the possibility of using the current syntax for the _keto_engine_acp_ory_ handler?

Thanks,

**Comment by aeneasr** [comment]
That sounds pretty good! My recommendation is to wait https://github.com/ory/oathkeeper/pull/334 to be merged (probably today) because it also touches some internals.

> About the AuthenticationSession structure, I can either add a RuleValues [] string field or add an array in Extra.

You want to store the parameters extracted from the URL matcher here, right?

**Comment by aeneasr** [comment]
> You want to store the parameters extracted from the URL matcher here, right?

If so, I would probably make it a struct:

```go
type MatchContext struct {
  RegexpCaptureGroups []string
  URL *url.URL
}
```

**Comment by Sbou** [comment]
Ok for the structure.

For the URL, we was thinking the full URL or just the part which match with the Regex ?

**Comment by Sbou** [comment]
I am not familiar with glob. Is it possible to extract groups as for a Regex?

Otherwise I add functionality only for regex and I leave the syntax for keto engine as is.

**Comment by Sbou** [comment]
I created a commit with some modifications. Befoire to create a pull request I would like validate if it's the good way to implement this feature.

Can you check the commit ?

I added this struct to **AuthenticationSession**
```go
type MatchContext struct {
  // Has the regexp capture groups
  RegexpCaptureGroups []string

  // The original url (with scheme, host, path, query params set)
  URL *url.URL
}
```

This struct is used only for Regex matching strategy.

I also added a go template function **printIndex** to avoid error when the index is out of range.
I don't know if it's a good idea ?

```go
"printIndex": func(element interface{}, i int) string {
				if element == nil {
					return ""
				}

				list := reflect.ValueOf(element)

				if list.Kind() == reflect.Slice && i < list.Len() {
					return fmt.Sprintf("%v", list.Index(i))
				}

				return ""
			},
```

Thanks,

**Comment by Sbou** [comment]
I can't create a docker image for oathkeeper.
When I run **make docker** I have this error:

```shell
build github.com/ory/oathkeeper: cannot load mnt/c/Repos/oathkeeper/packrd: malformed module path "mnt/c/Repos/oathkeeper/packrd": missing dot in first path element
Makefile:46: recipe for target 'docker' failed
make: *** [docker] Error 1
```

Have you got an idea ?

**Comment by aeneasr** [comment]
Windows?

**Comment by Sbou** [comment]
I use WSL on Windows

**Comment by aeneasr** [comment]
Ah ok, no idea unfortunately. I've used Windows in the past but never got WSL to work properly. I tried Docker on WSL but it never worked, native Docker for Windows instead usually worked for me. I've never seen that error message before (`missing dot in first path element`) so I'm really out of useful ideas here, sorry :|

**Comment by nihalgurjar47** [comment]
Hi @aeneasr,
I hope you doing well. 
My requirement is that if request comes from through the oath keeper like URL https://abc.com/api/v1/profile than i want to pass api/v1/profile in keto payload .

Example:-
- id: "ory:kratos-admin-ui-node-ui:protected"
      upstream:
        preserve_host: true
        url: "http://abc-frontend-clusterip:80/"
      match:
        url: "http://abc.com/api/v1/profile"
        methods:
          - GET
      authenticators:
        - handler: cookie_session
      authorizer:
        handler: remote_json
        config:
          remote: http://keto-api:4456/relation-tuples/check
          payload: |
              {
                "namespace": "access",
                "object": "/api/v1/profile",
                "relation": "access",
                "subject_id": "{{print .Extra.identity.metadata_public.role }}"
              }
      mutators:
        - handler: id_token
      errors:
        - handler: redirect
          config:
            to: http://abc.com/panel/login
            
  Every request path i want to pass dynamically.
  Thanks in advance
