### ISSUE TITLE
Caching in the oauth2_introspection authorizer

### ISSUE THREAD

**Issue by pike1212** [ory/oathkeeper#293]
**Is your feature request related to a problem? Please describe.**

oauth2_introspection authorizer may have to make multiple requests for every incoming token (one for the introspection, the other to get a token if using the pre_authorization step)

**Describe the solution you'd like**

I would like Oathkeeper to cache both incoming tokens and the pre_authorization token

**Comment by aeneasr** [comment]
Yeah that makes sense. Would you be up for a PR?

**Comment by pike1212** [comment]
Yes, we are working on one.

**Comment by aeneasr** [comment]
Awesome!
