### ISSUE TITLE
Error: unknown command "migrate" for "oathkeeper"

### ISSUE THREAD

**Issue by jiangytcn** [ory/oathkeeper#294]
Hi
I didn't find the migrate command under `cmd`, is this still necessary for 

https://github.com/ory/oathkeeper/blob/master/docker-compose.yml#L5-L15

 and the full stack tutorial 

https://github.com/ory/examples/blob/master/full-stack/docker-compose.yml#L30-L40

**Comment by aeneasr** [comment]
Yes, we've removed the need for a Database, hence `migrate` is obsolete.

We haven't updated the full-stack docker compose in a while (the version is very old).

We definitely will remove the entry from this project's docker-compose file!

**Comment by jiangytcn** [comment]
thanks @aeneasr  is there any page i can follow to create the whole solutions provided by ory, like to have a demo to see the capabilities before dive into each separate project. btw, the projects looks good (thumbs up +1)

**Comment by aeneasr** [comment]
the best place to start is ory.sh/docs

each project is standlone, you pick what you need, not the other way around
