### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by jakkab** [ory/oathkeeper#295]
**Is your feature request related to a problem? Please describe.**

It would be great if Oathkeeper supported prometheus metrics just like Hydra does:
https://www.ory.sh/docs/hydra/sdk/api#get-snapshot-metrics-from-the-hydra-service-if-you-re-using-k8s-you-can-then-add-annotations-to

**Describe the solution you'd like**

Prometheus metrics are accessible at `/metrics/prometheus`

**Comment by piotrmsc** [comment]
@jakkab totally agree! 
We should have proxy specific metrics as well as go specific metrics :)

What’ya think @aeneasr 
Later on I could provide a minimal set of metrics to be measured ?

**Comment by aeneasr** [comment]
Yes, makes sense! I think we have some shared libraries for this case, I’ll look into it later.

**Comment by aeneasr** [comment]
Yes, makes sense! I think we have some shared libraries for this case, I’ll look into it later.

**Comment by pike1212** [comment]
Would like to see metrics from the various caches as well, what needs to happen to enable metrics?

**Comment by aeneasr** [comment]
What kind of metrics?

**Comment by pike1212** [comment]
Ristretto provides `optional performance metrics for throughput, hit ratios, and other stats.` (I don't think we are setting the cost correctly for the cache)

**Comment by aeneasr** [comment]
Yeah the cost is completely random / based on their recommendations. It probably strongly depends on the use case. What issues are you experiencing?

**Comment by pike1212** [comment]
No issues yet, but not moving a high volume of requests through yet either, just trying to make sure it won't grow the cache too large when we do. Looks like cost is set to 0 which I don't think is ever going to evict items based on MaxCost, so worried it's really a straight TTL cache with no max size.

**Comment by aeneasr** [comment]
MaxCost of 0 means that Ristretto picks the cost itself iirc!

**Comment by pike1212** [comment]
We are not passing a coster function to the config, so I'm not sure that is correct

https://github.com/dgraph-io/ristretto/blob/master/cache.go#L242
```
// To dynamically evaluate the items cost using the Config.Coster function, set
// the cost parameter to 0 and Coster will be ran when needed in order to find
// the items true cost.
```

**Comment by aeneasr** [comment]
Oh I see, it might be a misinterpretation on my part! Any contributions towards this are highly welcomed!

**Comment by pike1212** [comment]
Yes, I'm going to look into fixing this, and maybe making the size of the caches configurable
