### ISSUE TITLE
cookie_session authenticator masks 401 errors

### ISSUE THREAD

**Issue by paulbdavis** [ory/oathkeeper#298]
**Describe the bug**

When the endpoint called by the `cookie_session` checker returns a 401, the proxy returns a 403

**Reproducing the bug**

1. Set up a `cookie_session` authenticator with a service that will return a 401 when the cookie in question is invalid
2. Attempt to access an endpoint using that authenticator

**Expected behavior**

I would expect the authenticator to return a 401 when the session checker returns a 401

**Environment**

- Version: v0.32.1-beta.1
- Environment: kubernetes

**Comment by aeneasr** [comment]
This is resolved on master by #315
