### ISSUE TITLE
token_from required for oauth2_introspection but ignores "seperated" values

### ISSUE THREAD

**Issue by pike1212** [ory/oathkeeper#308]
**Describe the bug**

The token_from field in oauth2_introspection appears to be required now, which is fine, but when I specify "Authorization" it no longer splits up the token field if the value is "Bearer _token_" in the BearerTokenFromRequest method.

**Comment by aeneasr** [comment]
I'm not sure I understand the issue?

**Comment by pike1212** [comment]
If my config looks like 

```
      token_from:
        header: Authorization
```
And the header is `Authroization: Bearer 12345`

Then oathkeeper will try to introspect `Bearer 12345` instead of just `12345`

https://github.com/ory/oathkeeper/blob/master/helper/bearer.go#L38

**Comment by aeneasr** [comment]
To use the `Authorization` header you should levae `token_from` empty. But I do understand that this is confusing, and that this should work properly. We should probably check here ( https://github.com/ory/oathkeeper/blob/master/helper/bearer.go#L40 ) if the value is `Authorization` or not and if it is, just skip the if and go to: https://github.com/ory/oathkeeper/blob/master/helper/bearer.go#L52

Would you be open for a PR?
