### ISSUE TITLE
Allow http client timeout to be configurable

### ISSUE THREAD

**Issue by pike1212** [ory/oathkeeper#310]
**Is your feature request related to a problem? Please describe.**

oauth2_introspection authenticator uses NewResilientClientLatencyToleranceSmall which sets a timeout of 500 milliseconds, this could be an issue in other authenticators/mutators as well.

**Describe the solution you'd like**

Perhaps env vars that the resilient_client will look for to override the default timeout?

**Comment by aeneasr** [comment]
Yes, we can make this configurable. Are you up for a PR?

**Comment by pike1212** [comment]
Yes, do you think it should be in the library, or configurable in oathkeeper and passed to the library?

**Comment by aeneasr** [comment]
Configurable in OK and passed to the lib :)
