### ISSUE TITLE
Replace the base image with alpine

### ISSUE THREAD

**Issue by niaiwomattt** [ory/oathkeeper#312]
In k8s, `scratch` mirroring is very inconvenient. You cannot execute commands such as mount ls, and you cannot debug the problem.

**Comment by aeneasr** [comment]
I guess we can switch over to an alpine-based image here. Would you be able to PR that?

**Comment by niaiwomattt** [comment]
> I guess we can switch over to an alpine-based image here. Would you be able to PR that?

I didn't succeed, `USER 1000` failed, I can't solve it, can you try it? If successfully transferred to hub.docker.com, share the address here, thank you!

**Comment by niaiwomattt** [comment]
Did your test succeed?

**Comment by niaiwomattt** [comment]
3 days ago you submitted the branch, when did you submit it to `hub.docker.com` If you did, hope to reply, thank you!

**Comment by aeneasr** [comment]
Hey, this is now released!

https://github.com/ory/oathkeeper/releases/tag/v0.33.1-beta.1
