### ISSUE TITLE
support the cookie as token source (token_from) for JWT authenticator

### ISSUE THREAD

**Issue by ngrigoriev** [ory/oathkeeper#330]
**Is your feature request related to a problem? Please describe.**

According to the Oathkeeper documentation the "jwt" authenticator can fetch the token from either a named HTTP header or from the query parameter. At the same time, "oauth2_introspection" authenticator supports the named cookie as source. It would be great to support the cookie source for "jwt" authenticator as well.

**Describe the solution you'd like**

I may be wrong but it looks like it may be already supported, authenticator_jwt.go calls helper.BearerTokenFromRequest() to get the token and this function does support all 3 sources. Is it possible that this is just a missed point in the documentation?

Thanks!

**Comment by aeneasr** [comment]
Yes, I believe this is just a docs issue!

**Comment by ngrigoriev** [comment]
I am trying to add the unit tests for this + update the schema
