### ISSUE TITLE
Pass query parameters to the hydrator

### ISSUE THREAD

**Issue by crabtree** [ory/oathkeeper#339]
**Is your feature request related to a problem? Please describe.**

In the current implementation, the hydrator calls the endpoint with the headers rewritten from the original response. In our case it would be also valuable to pass the query parameters from the original request.

**Describe the solution you'd like**

In the easiest approach, all query parameters from the original request can be rewritten to the hydrator API call. In a more sophisticated approach, there should be a configuration where we can define which query parameters should be rewritten to the API call.

**Comment by aeneasr** [comment]
Hi, yes, sorry for the late reply - this makes absolute sense.

**Comment by aeneasr** [comment]
This was resolved
