### ISSUE TITLE
Support for TLS certificate authentication

### ISSUE THREAD

**Issue by moritzheiber** [ory/oathkeeper#347]
I would like to be able to use TLS certificates to authenticate to Oathkeeper, i.e. Oathkeeper validating TLS certificates either against a remote CA or with a locally sourced CA.

Very simple use-case: Modern service meshes allow for seamless mutual TLS between service nodes inside Kubernetes clusters. Most of them (e.g. Envoy) also support forwarding these client TLS certificates to the service sitting behind the mesh proxy. You can then use these certificates to establish identity trust, including extracting subject information, with Oathkeeper.

I also considered using Oathkeepers JWT backend to validate Kubernetes service tokens, however, Kubernetes doesn't have an endpoint exposed [yet](https://github.com/kubernetes/kubernetes/pull/80724) for validating the JWT service tokens.

**Comment by aeneasr** [comment]
I'm pretty sure we support TLS, see [the config reference](https://www.ory.sh/docs/oathkeeper/configuration).

If you think there's a bug with the TLS implementation provide additional details please :)

**Comment by moritzheiber** [comment]
That's only for _connecting_ to Oathkeeper, though, right? None of the details in the certificate chain are exposed to the authn/authz flow?

I'm looking for a way of using TLS certificates as a means for authentication in the decision chain.

**Comment by aeneasr** [comment]
Ah right, my bad! So you want to supply a TLS Client Certificate for calls to remotes from oathkeeper and optionally include the TLS Client Certificate for upstream calls, right?

**Comment by moritzheiber** [comment]
Yes, and I would like to be able to use the information contained inside the certificate for policy decisions inside authorizers (in my case: Keto) as well (if possible), i.e. `AuthenticationSession` should be able to carry some metadata (ideally at least a valid `Subject`) towards the authorizer.

**Comment by aeneasr** [comment]
Yeah, so I thought we had an open issue for a mTLS authenticator but apparently we do not - there is sort of an umbrella issue für SPIFFE though (https://github.com/ory/oathkeeper/issues/247). I would definitely like to see such an mTLS authenticator in this project (and contributions are as always welcome :) )!

Regarding outgoing connections - do we need a separate client certificate for each outgoing call, or will the service get a global client certificate? I think we could easily add a small config setting to load the CC from and then inject it in the http.Client when making the calls. What do you think?

**Comment by moritzheiber** [comment]
I do believe the mTLS certificates in most meshes are connection specific, e.g. the certificate to connect Service A with Service B isn't the same as Service A to Service C (but I might be wrong, I didn't check).

And yes, that sounds reasonable.

Looking at #247, I feel like it does cover a lot of what I would want as well. One would need to verify though if the real world application is possible with the current "best practice" mesh implementations (Istio, Linkerd, Consul etc.).

**Comment by moritzheiber** [comment]
My research has shown that my intentions for this ticket will be fulfilled by #247, so I'm closing this ticket in favor of the other.
