### ISSUE TITLE
Iterate over all the available JWKs and see which one is valid when no KID is present on the JWT header

### ISSUE THREAD

**Issue by guillaumeH** [ory/oathkeeper#362]
**Is your feature request related to a problem? Please describe.**

I work with oathkeeper and I would like to set up a JWT token authentication with JWK to validate an external resource.
The problem I am currently experiencing is as follows, the JWT header I receive is as follows: **eyJhbGciOiAiUlMyNTYifQ**
Which gives us this:
```
{
  "alg": "RS256"
}
```
I configured oathkeeper to validate the token via JWKs provided, but unfortunately, the external service tells me that I have to go around the kid because they rotate.
And after some research, I see that oathkeeper expects to receive a kid in the header of the JWT ...

**Describe the solution you'd like**

Set up the possibility via the configuration of being able to have no kid in the header and in this case, to go around the JWKs available and see if one is valid.

**Describe alternatives you've considered**

Use x.509 certificates instead of JWKs, but not yet possible

**Additional context**

Here is the external service explanation :
https://github.com/subscriptions-project/swg-js/blob/master/docs/entitlements-flow.md#validate-entitlements

**Comment by aeneasr** [comment]
As discussed in discord, I think this is a good idea. Would you be open to contributing this feature?

**Comment by guillaumeH** [comment]
We have short deadline for our project, I wait for the response of the external service if they can add the KID in the token.
If not, yes we are open to contributing this feature.

**Comment by aeneasr** [comment]
Contributions welcome :)

**Comment by aeneasr** [comment]
Incorrect stalebot detection - this was assigned a milestone.
