### ISSUE TITLE
What is the format for the AUTHENTICATORS_OAUTH2_INTROSPECTION_CONFIG_INTROSPECTION_REQUEST_HEADERS environment variable in OathKeeper?

### ISSUE THREAD

**Issue by brentmoore** [ory/oathkeeper#366]
Asked this on the forum, nobody had an idea that worked. 

What is the format for the AUTHENTICATORS_OAUTH2_INTROSPECTION_CONFIG_INTROSPECTION_REQUEST_HEADERS environment variable in OathKeeper? I've tried a number of different options for "X-Forwarded-Proto: https" but can't seem to get something OathKeeper will accept.
 paulToday at 12:24 PM
@bdm:  Are you able try passing it in in a config file instead?
 bdmToday at 12:24 PM
No. I'm trying to use the default image in a AWS Fargate task. Using the config file requires me to build a custom image.
 paulToday at 12:26 PM
Take a look at the docs here https://github.com/spf13/viper

This is the lib being used to parse the config from the flags/file/env
GitHub
spf13/viper
Go configuration with fangs. Contribute to spf13/viper development by creating an account on GitHub.

[12:26 PM]
Specifically you are trying to pass in what will end up being a go map when it gets parsed
[12:29 PM]
From some basic googling you want AUTHENTICATORS_OAUTH2_INTROSPECTION_CONFIG_INTROSPECTION_REQUEST_HEADERS="{\"x-forwarded-proto\":\"https\"}"
[12:30 PM]
or you can try setting AUTHENTICATORS_OAUTH2_INTROSPECTION_CONFIG_INTROSPECTION_REQUEST_HEADERS_X-FORWARDED-PROTO=https (or the same, but replace the - with _, not sure how the env replacer is set up)
[12:30 PM]
but that first option should work
 bdmToday at 12:38 PM
First option gave: time="2020-02-21T19:37:35Z" level=fatal msg="The configuration is invalid and could not be loaded." error="must validate one and only one schema (oneOf)" validation_error[0]="authenticators.oauth2_introspection: Must validate one and only one schema (oneOf)" validation_error[1]="authenticators.oauth2_introspection.config.introspection_request_headers: Invalid type. Expected: object, given: string"
[12:38 PM]
Trying the second...
[12:43 PM]
OathKeeper doesn't seem to recognize it - gave no error but isn't including the header in introspection requests.
[12:43 PM]
Trying with _
[12:45 PM]
Didn't make a difference.
 paulToday at 12:46 PM
Hmm, I'm not sure then, those were my ideas
[12:47 PM]
@bdm: Is there a reason you need to run it that way vs. just running the docker container yourself?
 bdmToday at 1:10 PM
Trying to set up a pattern where we can deploy Hydra/OathKeeper via Terraform into any account that needs it. I was hoping to avoid having to build a custom image (and set up the corresponding AWS infrastructure to build, house, and manage it) when it is simply the base image plus a file that supposedly I can replace via environment variables.
 status_quo69Today at 1:14 PM
You don't have to build a custom image, you can mount a volume, right?
[1:14 PM]
Mount the volume and point oathkeeper at the config directory
 bdmToday at 1:16 PM
I can mount a volume, but currently Fargate supports ephemeral storage to be mounted. If I could get at other storage types it would be a non-issue.
 status_quo69Today at 1:17 PM
Oh wow. I've never played with fargate before, that seems not awesome
 bdmToday at 1:18 PM
Nope. Makes dealing with OathKeeper rules files an issue too. I miss the old API for defining rules.
[1:20 PM]
There are lots of things we like about Fargate, but like everything else there are a few things that cause issues.
 paulToday at 1:21 PM
Looks neat, but I think it's odd that you can't mount persistant storage on them
[1:22 PM]
You could use some sort of NAS or clustered storage, but then you'd be in the same place needing to build a custom image to use it so....
 bdmToday at 1:22 PM
I believe it is on the roadmap but not an option now (I'll ping our AWS support engineer).
[1:23 PM]
This is the only issue I haven't been able to solve. Everything else works like a charm.
 paulToday at 1:23 PM
Fargate seems like the kind of thing you could use for a majority of your infrastructure but you'll still need some bits running more traditionally
[1:24 PM]
That being said, you should be able to set that value via env var. File an issue on the repo

Any ideas on what the value should be?

**Comment by aeneasr** [comment]
Yeah viper is kind of limited here, not sure how that would work right now. Please use a config file if possible.

I am currently working with viper maintainers to improve the library so hopefully this will be possible in the future :)

**Comment by aeneasr** [comment]
I'm closing this in favor of #342 because it is the same underlying issue :)
