### ISSUE TITLE
Unable to use the hydrator mutator

### ISSUE THREAD

**Issue by henrikengelbrink** [ory/oathkeeper#380]
**Describe the bug**

I'm trying to use the Hydrator Mutator to turn the bearer token into a "X-User-Id" header which contains my internal backend userId.

**Reproducing the bug**

I'm running the following curl request:
```
curl --location --request PUT 'https://api.engelbrink.dev/device-service/devices' \
--header 'Authorization: Bearer XXXXXXXXXXXXX.ECtFk4lZ-KztOe0oHYO_JF7ECbtmvNJjtbjiNrOyXW0'
```

I get the following response:
```
{
    "error": {
        "code": 500,
        "message": "Post http://user-service:8585/auth/hydrator: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
    }
}
```

*Server logs*

```
time="2020-03-17T10:26:09Z" level=warning msg="The mutation handler encountered an error" access_url="http://api.engelbrink.dev/device-service/devices" authorization_handler=hydrator error="Post http://user-service:8585/auth/hydrator: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" granted=false reason_id=mutation_handler_error
time="2020-03-17T10:26:09Z" level=warning msg="Access request denied" access_url="http://api.engelbrink.dev/device-service/devices" error="Post http://user-service:8585/auth/hydrator: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" granted=false
time="2020-03-17T10:26:09Z" level=error msg="An error occurred while handling a request" code=500 debug= details="map[]" error="Post http://user-service:8585/auth/hydrator: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" reason= request-id= status=500 trace="Stack trace: \ngithub.com/ory/oathkeeper/pipeline/mutate.(*MutatorHydrator).Mutate.func1\n\t/go/src/github.com/ory/oathkeeper/pipeline/mutate/mutator_hydrator.go:131\ngithub.com/cenkalti/backoff.RetryNotify\n\t/go/pkg/mod/github.com/cenkalti/backoff@v2.1.1+incompatible/retry.go:37\ngithub.com/cenkalti/backoff.Retry\n\t/go/pkg/mod/github.com/cenkalti/backoff@v2.1.1+incompatible/retry.go:24\ngithub.com/ory/oathkeeper/pipeline/mutate.(*MutatorHydrator).Mutate\n\t/go/src/github.com/ory/oathkeeper/pipeline/mutate/mutator_hydrator.go:128\ngithub.com/ory/oathkeeper/proxy.(*RequestHandler).HandleRequest\n\t/go/src/github.com/ory/oathkeeper/proxy/request_handler.go:191\ngithub.com/ory/oathkeeper/proxy.(*Proxy).Director\n\t/go/src/github.com/ory/oathkeeper/proxy/proxy.go:116\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:216\ngithub.com/urfave/negroni.Wrap.func1\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP\n\t/go/pkg/mod/github.com/meatballhat/negroni-logrus@v0.0.0-20170801195057-31067281800f/middleware.go:136\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/x/metricsx.(*Service).ServeHTTP\n\t/go/pkg/mod/github.com/ory/x@v0.0.76/metricsx/middleware.go:261\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/urfave/negroni.(*Negroni).ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337" writer=JSON
time="2020-03-17T10:26:09Z" level=info msg="completed handling request" measure#oathkeeper-proxy.latency=3503809297 method=PUT remote="10.244.1.121:41816" request=/device-service/devices status=500 text_status="Internal Server Error" took=3.503809297s
```

*Server configuration*

This is my oathkeeper config file:
```yaml
oathkeeper:
  config:
    access_rules:
      repositories:
        - inline://${filebase64("${path.module}/oathkeeper-rules.json")}
    authenticators:
      noop:
        enabled: true
      oauth2_introspection:
        enabled: true
        config:
          introspection_url: http://hydra-admin:4445/oauth2/introspect
          scope_strategy: exact
          required_scope:
            - openid
            - offline
    authorizers:
      allow:
        enabled: true
    mutators:
      noop:
        enabled: true
      hydrator:
        enabled: true
        config:
          api:
            url: http://user-service:8585/auth/hydrator
```

This is the specific rule:
```json
{
    "id": "device-service-claim",
    "upstream": {
      "strip_path": "/device-service",
      "url": "http://device-service.services.svc.cluster.local:7979"
    },
    "match": {
      "url": "http://api.engelbrink.dev/device-service/devices",
      "methods": ["PUT"]
    },
    "authenticators": [
      {
        "handler": "oauth2_introspection",
        "config": {
          "introspection_url": "http://hydra-admin:4445/oauth2/introspect",
          "scope_strategy": "exact",
          "required_scope": ["openid", "offline"]
        }
      }
    ],
    "authorizer": { "handler": "allow" },
    "mutators": [
      {
        "handler": "hydrator",
        "config": {
          "api": {
            "url": "http://user-service:8585/auth/hydrator"
          }
        }
      }
    ],
    "errors": [{ "handler": "json" }]
  }
```

**Expected behavior**

I'm expecting oathkeeper hydrator  to connect to my custom backend and add the specific header to the request and forward it to the defined backend.

**Environment**

* Version:  "v0.0.48"
* Environment: Deployed with Helm in DigitalOcean managed Kubernetes cluster

**Additional context**

If I connect to my cluster and try to run the following curl command to my user-service:

```
curl --location --request POST 'http://localhost:8585/auth/hydrator' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer XXXXXXXXX.EuqjbTAMaUYVdw58PTAss2lOLLqyfaUkpoyWvY4uIVw' \
--data-raw '{
  "subject": "XXXXXXXXXX.DygsxJ_wkPA6PGGPdV4OpdBNOu53hma73oc_ivxLU2Q",
  "extra": {},
  "header": {}
}'
```

I get the following response:

```json
{
    "subject": "XXXXXXXXX.DygsxJ_wkPA6PGGPdV4OpdBNOu53hma73oc_ivxLU2Q",
    "header": {
        "X-User-Id": "28426fa8-54ea-40f6-acbd-a317d18b8f03"
    }
}
```

I think the implementation in my user-service works as expected and returns the right format.

Does anyone has an idea where the problem might be ?

**Comment by aeneasr** [comment]
Yeah `http://user-service:8585/auth/hydrator` looks to be the wrong URL (or something in the pipe fails) as the connection fails with a timeout, see the log message:

> Post http://user-service:8585/auth/hydrator: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by henrikengelbrink** [comment]
I checked everything, if I create a container in the same namespace like Oathkeeper, Hydra and my user-service, I'm able to curl the endpoint:

```
kubectl run --rm -i --tty busybox -n=auth --image=radial/busyboxplus:curl --restart=Never -- sh
```

```
root@busybox: $ curl --location --request POST 'http://user-service:8585/auth/hydrator' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer XXXX.EuqjbTAMaUYVdw58PTAss2lOLLqyfaUkpoyWvY4uIVw' \
--data-raw '{
  "subject": "XXXX.DygsxJ_wkPA6PGGPdV4OpdBNOu53hma73oc_ivxLU2Q",
  "extra": {},
  "header": {}
}'
```

This gives the following response:
```
{
    "subject": "XXXX.DygsxJ_wkPA6PGGPdV4OpdBNOu53hma73oc_ivxLU2Q",
    "header": {
        "X-User-Id": "XXX-54ea-40f6-acbd-a317d18b8f03"
    }
}
```

So the communication between the services in the cluster seems to work.

**Comment by aeneasr** [comment]
What do your application logs in `http://user-service:8585/` say? Do they get something from Hydra?

**Comment by henrikengelbrink** [comment]
Yes, I'm using the introspect endpoint of Hydra to get the subject from the token and with this subject I'm getting the userId from my database. The user-service also returns the JSON response.

**Comment by aeneasr** [comment]
How long does one network roundtrip take? You can do `time curl --location...`

**Comment by henrikengelbrink** [comment]
The result of this time command is the following:
real	0m 1.53s
user	0m 0.00s
sys	0m 0.00s

**Comment by henrikengelbrink** [comment]
I updated the config to exclude any timing problems:
```yaml
hydrator:
        enabled: true
        config:
          api:
            url: http://user-service:8585/auth/hydrator
          retry:
            give_up_after: 3s
            max_delay: 500ms
```

Now I'm getting thw following error message:
```json
{
    "error": {
        "code": 500,
        "status": "Internal Server Error",
        "reason": "Configuration for mutator \"hydrator\" could not be validated: json: unknown field \"retry\"",
        "message": "mutator matching this route is misconfigured or disabled"
    }
}
```

**Comment by aeneasr** [comment]
Retry is part of the API key, as documented here: https://www.ory.sh/docs/next/oathkeeper/pipeline/mutator#configuration-4

> The result of this time command is the following:
real	0m 1.53s

Wow that's a long time! That's probably why Oathkeeper canceled the request. You should set `max_delay` to 2 seconds and `give_up_after` to like 6 or 10

**Comment by henrikengelbrink** [comment]
I'm using the retry configuration now, but now I'm getting this message:
```json
{
    "error": {
        "code": 500,
        "status": "Internal Server Error",
        "reason": "Configuration for mutator \"hydrator\" could not be validated: json: unknown field \"give_up_after\"",
        "message": "mutator matching this route is misconfigured or disabled"
    }
}
```
Do you have any idea how to fix this problem ?

**Comment by aeneasr** [comment]
You're probably not using the most recent version, check the oryOS and see that it matches the docs

**Comment by henrikengelbrink** [comment]
Thank you for your effort!

I configured the Helm Chart now to use the image version `v0.36.0-beta.4` and the unknown field error is gone, but I'm getting the following error now:

```
time="2020-03-17T15:33:02Z" level=error msg="An error occurred while handling a request" code=500 debug= details="map[]" error="An internal server error occurred, please contact the system administrator" reason= request-id= status=500 trace="Stack trace: \ngithub.com/ory/oathkeeper/pipeline/mutate.(*MutatorHydrator).Mutate\n\t/home/ory/pipeline/mutate/mutator_hydrator.go:164\ngithub.com/ory/oathkeeper/proxy.(*RequestHandler).HandleRequest\n\t/home/ory/proxy/request_handler.go:315\ngithub.com/ory/oathkeeper/proxy.(*Proxy).Director\n\t/home/ory/proxy/proxy.go:134\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:206\ngithub.com/urfave/negroni.Wrap.func1\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/x/reqlog.(*Middleware).ServeHTTP\n\t/go/pkg/mod/github.com/ory/x@v0.0.93/reqlog/middleware.go:140\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/x/metricsx.(*Service).ServeHTTP\n\t/go/pkg/mod/github.com/ory/x@v0.0.93/metricsx/middleware.go:261\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/urfave/negroni.(*Negroni).ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357" writer=JSON
```

The request is not going into my service with the hydrator endpoint.

**Comment by aeneasr** [comment]
If you check the payload that is returned by Oathkeeper (the acutal JSON), you will probably see a message like:

> The call to an external API returned a non-200 HTTP response

I'm happy to help you but try continuing on your own for now and if you really can't figure it out we can take another look. To me, this looks like a configuration and upstream service issue.

**Comment by henrikengelbrink** [comment]
This is the json response I get from Oathkeeper:
```json
{
    "error": {
        "code": 500,
        "status": "Internal Server Error",
        "message": "An internal server error occurred, please contact the system administrator"
    }
}
```

Thank you for your help so far. I'll try to debug my system a little bit more and try to figure out what is the problem.

**Comment by aeneasr** [comment]
Were you able to figure out the problem? Are you using self-signed TLS certificates by any chance?

**Comment by catper** [comment]
this is a slightly different situation by i am also seeing issues with hydrator: oathkeeper reports `error="The call to an external API returned a non-200 HTTP response"` but the external service's logs indicate that everything is fine and a simple curl returns with a 200 response in 0.01 s

config:
```
  "mutators": [
           {
                "handler": "hydrator",
                "config": {
                    "api": {
                        "url": "http://external-service:8080/auth"
                    }
                }
            },
...
```
oathkeeper image: oryd/oathkeeper:v0.37.1-alpine

any idea what this might be about?

**Comment by aeneasr** [comment]
Not without additional details unfortunately. Best would be creating a new issue with the template filled out.

**Comment by aeneasr** [comment]
Or use the issue template and post it here :)

**Comment by aliadnani** [comment]
Had a similar issue running Oathkeeper on a Docker container and found it it was because the networking wasn't configured properly.

Was running my custom hydrator mutator API on my local machine `localhost:3040` but realized that Oathkeeper running in its own container wouldn't be able to resolve localhost properly. Quick fix was to use my host's network IP (ie. 192.168.8.52) in the config and access rule for testing until I could assign a proper public IP to my API.

**Comment by alan994** [comment]
Hi, I have a similar issue as well. In my case, I have the `Oath Keeper` rule that calls my API (hydrator mutator). In my app, I see logs and also have a breakpoint that is hit each time. For now, API is stupid and only adds two additional headers in the `header` property. The funny thing is when my upstream service is called those two headers are passed but the value for both is `""` (empty string).  

Here is a sample payload from my hydrator API
```
{
    "subject": "some string",
    "extra": {},
    "header": {
        "x-tl-user-id": [
            "alan994"
        ],
        "x-tl-company-id": [
            "aj-solutions",
            "talentlyft"
        ]
    }
}
```

Here are logs from my upstream service that shows that two headers are present, but without value
![image](https://user-images.githubusercontent.com/8849512/159342625-d30499eb-8c1c-42f1-b7c7-57584393cd6e.png)


In `Oath Keeper` [logs](https://pastebin.com/kAJCcpiS), I can't find anything useful. I enabled sensitive data logging and debug level. 

I'm running everything in `docker-compose`

`Oath Keeper` image: `oryd/oathkeeper:v0.38`

**Comment by tschlaepfer** [comment]
I experience the same issue regarding the empty headers in the upstream service.

**Comment by aeneasr** [comment]
Thank you all, I thiink we have identified the issue and merged a fix to master which will be released in about 2-3 weeks. You can also use `make docker` in the project's root to build your own docker image off of master for now.
