### ISSUE TITLE
Allow cookie_session authentication to have configurable Method for request to the check_session_url

### ISSUE THREAD

**Issue by MrShroom** [ory/oathkeeper#381]
**Is your feature request related to a problem? Please describe.**

While using Kratos, any POST request were not properly being authenticated via the kratos cookie session. This was because Oathkeeper uses the same request method to send request to the check_session_url as the request it is trying to authenticate.

**Describe the solution you'd like**

An option to be added to the oathkeeper configuration file under 
authenticators:
  cookie_session:
        config:
that forces all request to the check_session_url to the specified method. 

**Describe alternatives you've considered**

Changing the Kratos API code to allow POST requests on the sessions/whoami endpoint.

**Additional context**

This only affect cookies session authentication.

**Comment by aeneasr** [comment]
Thank you for the report! This has already been fixed on Kratos master but not yet released. Sorry for the debug hunt of something that's already fixed on master. Unfortunately, it will take more time to make another release as we're inbetween features.
