### ISSUE TITLE
Log Rule Id on malformed configuration error

### ISSUE THREAD

**Issue by hefekranz** [ory/oathkeeper#383]
**Is your feature request related to a problem? Please describe.**

When having a big pile of rules and a single config error among them, it's pretty hard to figure out which one it is. 

**Describe the solution you'd like**

I'd like to see the Id of the rule with the error in the logs. 
https://github.com/ory/oathkeeper/blob/a76f749dfe5c6ad988da6ba0b2ac4be5a22b0f9d/rule/repository_memory.go#L114
**Describe alternatives you've considered**

I used a fork to figure out which rules were flawed.
**Additional context**

I can push a PR if you are ok with that.

**Comment by aeneasr** [comment]
Totally makes sense! PRs appreciated!
