### ISSUE TITLE
Can't start version 0.19.0-beta.1

### ISSUE THREAD

**Issue by uepoch** [ory/oathkeeper#400]
**Describe the bug**
Since a few hours ago the schemas disppeared from the master branch in .schemas
This prevent all builds on 0.19.1.beta.1 to start due to direct linking to master branch
Similar to #397 

*Server configuration*

**Expected behavior**

Answers requests and does not breaks without alteration

**Environment**
Version 0.19.0-beta1
* Version: v1.2.3, git sha hash
* Environment: Debian, Docker, ...

**Additional context**

**Comment by uepoch** [comment]
@aeneasr

**Comment by uepoch** [comment]
It also prevented our production instance to continue working as is

**Comment by aeneasr** [comment]
Ok, we can re-add that to get old versions running again. Please subscribe to [the newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53) to be notified when new versions are out. I recommend upgrading when patches are out.

**Comment by uepoch** [comment]
Thanks for putting them back :), we will upgrade to the latest version

**Comment by aeneasr** [comment]
np, glad I could help
