### ISSUE TITLE
Add endpoint for answering access requests directly

### ISSUE THREAD

**Issue by arekkas** [ory/oathkeeper#42]

**Comment by euank** [comment]
Mind fleshing out some detail here? I'm not quite sure what you mean from just the title.

**Comment by arekkas** [comment]
The idea here is that we have an endpoint which is capable of answering requests based on the rules defined in oathkeeper, but without the proxy capability. So a bit like the warden endpoint + access rule :)

**Comment by calind** [comment]
@arekkas, this means it can be used with nginx [auth_request](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html) module?

**Comment by arekkas** [comment]
Yes, looks like it would!

**Comment by calind** [comment]
Cool. That would be pretty awesome.

**Comment by arekkas** [comment]
Good discussion on this in the [ambassador slack channel](https://datawire-oss.slack.com). I think their design approach is really good on this, see: https://www.getambassador.io/reference/services/auth-service

**Comment by robertrbruno** [comment]
Was researching nice out of the box ways to integrate oauth with ambassador.  Saw the slack channel discussion and sounds like this would go a long way of making it happen.  Hoping this happens.

**Comment by arekkas** [comment]
It shouldn't be very hard to add this functionality as it's basically all here already, especially since we're answering those requests based on the HTTP protocol itself, which is what we're already doing for the proxy. What would change is obviously the response but that is not hard to deal with. There are still other issues that need to be addressed by our team first, but it's on the list!

**Comment by robertrbruno** [comment]
Awesome.  Any order of magnitude time estimate on when this may happen.  As in weeks, months, years?  Thanks!

**Comment by arekkas** [comment]
Can't guarantee anything, definitely not years nor many months, maybe 4-8 weeks.

**Comment by robertrbruno** [comment]
Thanks.  Just was looking for a rough estimate to decide if I can wait a bit for this.  I'll keep an eye out for sure.
