### ISSUE TITLE
Remote ACCESS_RULES_REPOSITORIES should support redirects

### ISSUE THREAD

**Issue by tomlarkworthy** [ory/oathkeeper#425]
**Is your feature request related to a problem? Please describe.**

Resolver does not chase redirects. e.g. Google Cloud Storage (https://storage.cloud.google.com)

**Describe the solution you'd like**

rules served from Google Cloud Storage should work.

**Describe alternatives you've considered**

A work around exists, use the googleapis domain:-
https://storage.googleapis.com
Though this is not the URL exposed in the Google Cloud console.
(see https://stackoverflow.com/questions/59528183/how-to-prevent-google-cloud-storage-redirect)

**Comment by tomlarkworthy** [comment]
Oh also it throws unhelpful error messages which do not help diagnose the issue:-

Unable to update access rules from given location, changes will be ignored. Check the configuration or restart the service if the issue persists." error="error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context

I think this is coz the 302 is an empty body "" which it tries to decode as JSON

**Comment by tomlarkworthy** [comment]
work around is far from ideal as it only works with anonymous access

**Comment by aeneasr** [comment]
Are you sure a broken redirect is the problem? The Go stdlib for net/http follows up to 10 redirects!

**Comment by tomlarkworthy** [comment]
OK I tested it with curl more. The first response is a 302 but then following that ends in some kind of SSO page. On the browser I end up at the right place. So I guess it is a non obvious permission problem (very non obvious as the file has public access!).

I guess I might not be able to solve this without a Bearer token in the fetch, which for Google Cloud I can GET from the local metadata server.

**Comment by aeneasr** [comment]
Ok, so this is nothing we can fix right now in ORY Oathkeeper?

**Comment by tomlarkworthy** [comment]
yeah I don't think so, sorry, false diagnosis.
