### ISSUE TITLE
Can't disable profiling?

### ISSUE THREAD

**Issue by gdbinit** [ory/oathkeeper#435]
**Describe the bug**

No profiling is set on config.yaml and the 9000 port is still open and Go profiling active.

**Reproducing the bug**

```bash
./oathkeeper --config config.yaml serve --disable-telemetry --sqa-opt-out
INFO[0000] Config file loaded successfully.              path=config.yaml
Thank you for using ORY Oathkeeper v0.38.1-beta.1!

Take security seriously and subscribe to the ORY Security Newsletter. Stay on top of new patches and security insights.                                                                                                

>> Subscribe now: http://eepurl.com/di390P <<
INFO[0000] No tracer configured - skipping tracing setup 
INFO[0000] Setting up HTTPS for proxy                   
INFO[0000] TLS has not been configured for api, skipping 
INFO[0000] Listening on https://:443                    
INFO[0000] Listening on http://127.0.0.1:4456           
INFO[0000] Listening on http://:9000          
```

_Server configuration_

```yaml
# cat config.yaml 
serve:
  proxy:
    port: 443 # run the proxy at port 4455
    tls:
      key:
        path: /home/oathkeeper/key.pem
      cert:
        path: /home/oathkeeper/cert.crt

  api:
    port: 4456 # run the api at port 4456
    host: 127.0.0.1

access_rules:
  repositories:
    - file:///home/oathkeeper/rules.json

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: https://www.ory.sh/docs

mutators:
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject }}"
        # You could add some other headers, for example with data from the
        # session.
        # X-Some-Arbitrary-Data: "{{ print .Extra.some.arbitrary.data }}"
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

authenticators:
  noop:
    enabled: true
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: http://127.0.0.1:4445/oauth2/introspect
      pre_authorization:
        enabled: false
      cache:
        enabled: true
        ttl: 60s
```

**Expected behavior**

Profiling to be disabled unless explicitly configured.

**Environment**

- Version: v1.2.3, git sha hash
- Environment: Debian, Docker, ...

**Additional context**

**Comment by aeneasr** [comment]
Port 9000 is the Prometheus metrics exporter, it can not be disabled but has also no disadvantages. It only exposes stuff like memory used. So this has nothing to do with SQA :)

**Comment by gdbinit** [comment]
It's not locally, listen on all interfaces by default unless configured (I would expect default to be localhost unless explicit). I know it's not related to SQA, I don't want any telemetry out anyway.

**Comment by gdbinit** [comment]
serve:
  proxy:
    port: 443 # run the proxy at port 4455
    tls:
      key:
        path: /home/oathkeeper/key.pem
      cert:
        path: /home/oathkeeper/cert.crt
  api:
    port: 4456 # run the api at port 4456
    host: 127.0.0.1
  prometheus:
    port: 9000
    host: localhost
    metrics_path: /metrics

# ./oathkeeper --config config.yaml serve --disable-telemetry --sqa-opt-out
INFO[0000] Config file loaded successfully.              path=config.yaml
FATA[0000] The configuration is invalid and could not be loaded.  [config_key=serve]="additionalProperties \"prometheus\" not allowed" config_file=config.yaml

**Comment by aeneasr** [comment]
Right, we could change the host to default to localhost. We could also add a setting to disable it. Any particular reason why you don't want it to collect memstats other than that you don't need it? Is there any significant overhead, security implications, or something else?

**Comment by gdbinit** [comment]
I'm old school surface minimisation kind of guy. Also a fan of flexible configuration since computers are great for that. And it's a waste of cpu cycles if I don't really need the option.
It seems the commit for this is incomplete because the .schema doesn't have these options defined, so unconfigurable right now?

**Comment by aeneasr** [comment]
Right, looks like the original author overlooked that and so did I during review. If you'd be up for a contribution, that would be appreciated! You could both introduce en/disable and a default port of localhost :)

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
