### ISSUE TITLE
Support context field in the authorizer handler

### ISSUE THREAD

**Issue by msimonelli331** [ory/oathkeeper#439]
Keto supports conditions in their policy engine. To check against these conditions you need to send a payload with the "context" key. Oathkeeper should be able to build the payload with the context key, not just action, resource, and subject.

**Comment by iAziz786** [comment]
I'm happy to pick this up.

**Comment by aeneasr** [comment]
Nice, I think you can take a look at e.g. the remote json thing to figure this out for keto :)

**Comment by iAziz786** [comment]
Yes, I'm working on that. I have a few queries. Can you please elaborate on why are we returning only `remoteIpAddress` alongside `requestedAt` at the line below?

https://github.com/ory/oathkeeper/blob/2734906460e89ed9aedf5a48d0be2e8494d93df5/pipeline/authz/keto_engine_acp_ory.go#L81

**Comment by aeneasr** [comment]
The code is pretty old - I was also thinking that we could probably use the remote json authorizer to talk to keto and don't need the keto authorizer at all any more.

**Comment by iAziz786** [comment]
Okay, so for the entire Keto support we will be relying on remote JSON?

Do we need it to delegate through code or should we mention that in the docs?

**Comment by aeneasr** [comment]
Yeah I think so! It can do everything the keto authorizer can do as well but is more flexible. This definitely would need to be updated in the docs. I also want to switch to JsonNet #423 to make this easier.

**Comment by iAziz786** [comment]
Yeah, that's reasonable. Should we start working on that instead and once that's finished then working on this would be seamless?

Digging under I found that there is an already [Golang implementation](https://github.com/google/go-jsonnet) for that by Google. Have we considered using JSONnet in any other Ory projects before?

**Comment by aeneasr** [comment]
> Yeah, that's reasonable. Should we start working on that instead and once that's finished then working on this would be seamless?

Yes I think that makes sense. We would however first need to figure out how to ensure backwards compatibility with existing rules. I have some ideas, but currently no time to work on it. Maybe we document remote_json with current go templates first for keto?

**Comment by iAziz786** [comment]
Just saw #441 and I think is really a great idea to first clear things and then after start working. I think we can wait once RFC is finalized. What do you think?

**Comment by aeneasr** [comment]
SGTM
