### ISSUE TITLE
Original host lost after oathkeeper proxy

### ISSUE THREAD

**Issue by pike1212** [ory/oathkeeper#444]
**Is your feature request related to a problem? Please describe.**

Running Oathkeeper as a sidecar, and our container behind Oathkeeper needs access to the original protocol/host/port for redirects and other purposes, but only sees the host as localhost.

**Describe the solution you'd like**

I  think Oathkeeper needs ability to set `X-Forwarded-Host`, but am open to suggestions.

**Comment by aeneasr** [comment]
This is configurable per route using `preserve_host`. If `preserve_host: true`, the `Host` header will be the original host. If this is not solving your problem, feel free to comment/reopen!
