### ISSUE TITLE
Working with NGINX auth_request

### ISSUE THREAD

**Issue by ecktom** [ory/oathkeeper#461]
NGINX is able to do authentication based on subrequest results using the auth_request directive. We're using this heavily with Oathkeeper as backing service.

NGINX however expects the subrequest to return either 200, 401 oder 403 as response code. If we're forwarding a request to Oathkeeper for which no rules are defined 404 is returned. For the NGINX this looks like the auth backend is not available. Thus the incoming request get's responded with 500.

Easiest fix for this might be making the response status code for the no rules available case configurable. Would you be up for a PR to implement this behavior?

**Comment by aeneasr** [comment]
I think responding with a 403 when no rule matches is probably generally more in line with what would be expected? For me this is a go. Since the next version will include several breaking changes, I think we can add this as well.

**Comment by lanphan** [comment]
Hi @ecktom ,
We're trying ory ecosystem with setting oathkeeper + kratos behind nginx. I did 1 example about that here https://github.com/lanphan/example-oathkeeper, but seems it doesn't work correctly:
* open login page --> lots of <flow-id> are generated and stored in selfservice_login_flows
* cannot register new user

Would you please help me to take a look and give me some advice?
Thanks so much.

**Comment by ecktom** [comment]
Hi @lanphan,
I just had a quick look on your repo. The NGINX configuration for `auth_request` does look sufficient and should work. You could easily verify this by adjusting the Oathkeeper rules to something like:
```
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
```
which should let any request through. I think your issues are at the misconfigured `cookie_session` authentication handler which I however cannot help with. I would suggest you pop up at the Ory Slack and try to get some help from people which have used kratos before
