### ISSUE TITLE
[oathkeeper MacOS] Results not as expected per example

### ISSUE THREAD

**Issue by DarkBlaez** [ory/oathkeeper#476]
Per this link:
https://www.ory.sh/api-access-control-kubernetes-cloud-native/

When I try to exercise oathkeeper on MacOS and have created the access-rule-oathkeeper.json exactly as indicated I get nothing. Essentially oathkeeper just spits this out:

Usage:
  oathkeeper rules [flags]
  oathkeeper rules [command]

Available Commands:
  get         Get access rule
  list        List access rules

Flags:
  -e, --endpoint string   The endpoint URL of ORY Oathkeeper's management API
  -h, --help              help for rules

Global Flags:
  -c, --config string   Path to config file. Supports .json, .yaml, .yml, .toml. Default is "$HOME/.oathkeeper.(yaml|yml|toml|json)"

Use "oathkeeper rules [command] --help" for more information about a command.

No matter what I do...

The command as per the instructs is sent: 
oathkeeper rules --endpoint  http://${AMBASSADOR_IP}/ory-oathkeeper import access-rule-oathkeeper.json

AMBASSADOR_IP is set to the IP address which I have assigned through the LoadBalancer and everything is up and running.

I would like for oathkeeper to be explicit in the potential error not just keep giving me the options. Was this bin compiled correctly?

Also, odd behavior I am seeing and this is a separate issue but curious if others have run in to it. When I use curl to check status of the endpoint (curl  http://${AMBASSADOR_IP}/ory-oathkeeper/health/alive) I get nothing, just empty result , no json. When I use the web browser to check the endpoint I will get the {"status":"ok"}. The browser will roll it to an https endpoint.

If I then try to curl the endpoint as an https it will look for certs

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

I'm more interested in getting oathkeeper working correctly as the instructions are step by step. The curl issue I can try to work around and spin up a Linux VM to see what is going on.

Help
thanks
DB

**Comment by DarkBlaez** [comment]
In trying to get more info from the second issue with curl. I spit out the verbose output:
% curl -v http://${AMBASSADOR_IP}/ory-oathkeeper/health/alive

*   Trying 10.25.0.200...
* TCP_NODELAY set
* Connected to 10.25.0.200 (10.25.0.200) port 80 (#0)
> GET /ory-oathkeeper/health/alive HTTP/1.1
> Host: 10.25.0.200
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< location: https://10.25.0.200/ory-oathkeeper/health/alive
< date: Mon, 06 Jul 2020 21:12:32 GMT
< server: envoy
< content-length: 0
<
* Connection #0 to host 10.25.0.200 left intact
* Closing connection 0

Why would curl-ing this show error 301 Moved Permanently but going through a browser I get the correct status?

Also, I tried the dockerized version of oathkeeper to rule in/out MacOS and it appears the same result is occurring with this dockerized version. How can I get detailed output from oathkeeper? I am assuming it is running in to the same issue that curl is. This then looks to be something Ambassador is doing.

thanks
DB

**Comment by DarkBlaez** [comment]
I am able to exercise the APIs with curls as follows:

curl -v -k https://10.25.0.200/ory-oathkeeper/version

I am at a loss as to why oathkeeper is not functioning. Is there a way to make output verbose? Can we add a flag to resolve perhaps what might be a cert issue. I think within this posted issue there is enough presented that should either point me in the right direction or have additional options made available within the oathkeeper client

Thanks
DB

**Comment by aeneasr** [comment]
Without server side logs, it will be very hard to debug. It would be great if you could follow the issue template and include a reproducible test case. Otherwise I'm just playing a guessing game.

Additionally, please note that the guide is pretty dated (2 years old!) and that current versions of Oathkeeper are not compatible with the version used there. Ambassador has also changed in these 2 years.

**Comment by DarkBlaez** [comment]
Thanks for the reply. I was unaware the examples was that far out of date and has not been updated. I will review the docs and see where the deltas are. However, verbose output from the oathkeeper client would be helpful. I can curl the endpoint and will exercise without the client until I can track down the issue
