### ISSUE TITLE
Throwing an error for using "-" 

### ISSUE THREAD

**Issue by monarkatfactly** [ory/oathkeeper#477]
**Describe the bug**

Client sending “X-Space” header in request. So I want to use that header in keto_engine_acp_ory Authorizer for construction of the required_action and required_resource.

But it’s throwing error that regarding “-”.

So I removed “-” from the header so now header became only “space” and still it’s not working
It sending “[]” instead of header value.

**Reproducing the bug**

_Server logs_
```
{
  "error": {
    "code": 500,
    "message": "template: ee7bf07b822edce5eaec7bf8b96115b314a1ce04750c1a2dfcc56ce012d6c245:1: bad character U+002D '-'"
  }
}
```
_Server configuration_
`
{
  "authorizer": {
    "handler": "keto_engine_acp_ory",
    "config": {
      "required_action": "...",
      "required_resource": "resources:org:{{ .Headers.X-Organisation }}:tags"
      "subject": "{{ .Extra.email }}",
      "flavor": "regex"
    }
  }
}
`

**Expected behavior**

How to use "-" in header

**Comment by aeneasr** [comment]
```
.Headers["X-Organisation"]
```

should be correct
