### ISSUE TITLE
[Question] MySQL / Postgres for persisting rules

### ISSUE THREAD

**Issue by DarkBlaez** [ory/oathkeeper#478]
In the examples which I am told are dated from 2018 (why are they not updated) it references that MySQL/Postgres can be used

"This configuration sets up the ORY Oathkeeper API with an in-memory database (please note, that restarting the service will remove all existing data!). ORY Oathkeeper can connect to other database backends such as MySQL or PostgreSQL for persistence."

However, in reviewing the Helm chart I see no config option for such. In reviewing the online documentation I see no reference and most of the references are with straight up docker containers.

If this is being persisted as files then from what I gather a restart will wipe these out. If a DB backend is not being used per the quoted 2018 reference then the Helm chart should contain a persistence option.

Please clarify, thanks
DB

**Comment by aeneasr** [comment]
What example are you refering to?

Current versions of oathkeeper no longer need a database.

**Comment by DarkBlaez** [comment]
https://www.ory.sh/api-access-control-kubernetes-cloud-native/

That's good to know, so I won't worry about it, seems I have everything working now but was just wondering. Thanks

**Comment by aeneasr** [comment]
Nice!
