### ISSUE TITLE
remote_json: Enable timeout configuration for calls to authorization endpoint

### ISSUE THREAD

**Issue by Sbou** [ory/oathkeeper#515]
**Is your feature request related to a problem? Please describe.**

When running on Kubernetes with remote_json we find that the call to the authorization endpoint often times out. The default timeout is 500 milliseconds, which is a long time and should be enough but we find that for our setup, it generally isn't.

**Describe the solution you'd like**
I'd like to be able to specify a timeout for the request to the authorization endpoint so that we are not hindered by things that really should be circumventable. Something akin to the retry config that you can set for authorization should do the trick.

**Describe alternatives you've considered**

**Additional context**

**Comment by aeneasr** [comment]
Sounds good, contributions appreciated!

**Comment by Kortivex** [comment]
Can be this applies to the 'remote' authorizer too?

**Comment by aeneasr** [comment]
Yes!
