### ISSUE TITLE
Enable forwarding of original authorization header to (remote) authorizer

### ISSUE THREAD

**Issue by catper** [ory/oathkeeper#528]
**Is your feature request related to a problem? Please describe.**

Authorization is typically done on the subject but there may be additional information in the access token that is needed for a decision to be made. At present, it doesn't seem possible to forward the original access token to a remote authorizer though, you can only forward data that exists within the authSession object can be passed on.

**Describe the solution you'd like**

I'd like the auth header to be forwarded to the remote authorizer.

**Comment by aeneasr** [comment]
Thank you! This makes definite sense and will be part of https://github.com/ory/oathkeeper/issues/441 once we work on it :)

**Comment by catper** [comment]
While waiting for #441 to happen, would it be acceptable to implement this as "stand alone" feature? I'm thinking all that's needed is a single line, copying the auth header and then we'd be done?

**Comment by ashneverdawn** [comment]
I'm interested in this too.

**Comment by aeneasr** [comment]
Yes, sounds good! Open to contributions! :)
