### ISSUE TITLE
Documentation of oauth2_introspection authenticator not up to date

### ISSUE THREAD

**Issue by epandurski** [ory/oathkeeper#549]
https://www.ory.sh/oathkeeper/docs/pipeline/authn#oauth2_introspection

This page does not mention the audience/target_audience field or whether it is verified by the authenticator. By looking at the code it seems that there is a verification for it. The documentation is lacking this information.

**Comment by aeneasr** [comment]
Would you be open to add this info to the documentation? :)

**Comment by epandurski** [comment]
Yes, but the problem is that my knowledge of Go is practically zero, and I could not reliably understand the code without first learning quite a lot.
