### ISSUE TITLE
Authenticator oauth2_introspection only works if token_type returned is an "access_token"

### ISSUE THREAD

**Issue by daviddelucca** [ory/oathkeeper#553]
**Describe the bug**

When the introspect URL returns a token_type that is not an `access_token`, Oathkeeper throws an exception:

```
Introspected token is not an access token but "..."
```

This error is related to this [validation](https://github.com/ory/oathkeeper/blob/master/pipeline/authn/authenticator_oauth2_introspection.go#L171-L173).

**Reproducing the bug**

_Server logs_

```
time="2020-10-07T20:41:47Z" level=error msg="An error occurred while handling a request" code=403 debug= details="map[]" error="Access credentials are not sufficient to access this resource" reason="Introspected token is not an access token but \"Bearer\"" request-id=53e06937-f10a-4164-9f6e-d1a2ef2224fd status=403 writer=JSON
```

**Expected behavior**

It should accept other token_types instead of works only with access_token.

**Environment**

- Version: v0.38.2-beta.1
- Environment: Ory Helm Chart 

**Additional context**

If the solution is simple like remove that [validation](https://github.com/ory/oathkeeper/blob/master/pipeline/authn/authenticator_oauth2_introspection.go#L171-L173) or validate the `token_type` accross a few values, I could open a PR for it. I have read [RFC](https://tools.ietf.org/html/rfc7662#page-4) and I didn't find what are the expected values or if there are any.

**Comment by aeneasr** [comment]
Yes we should change that - the token_type is Bearer. We'll be introducing a new `token_use` in the introspection response which would then be access token for example. I think we should fix this here!

**Comment by aeneasr** [comment]
Would you be up to contributing that change?

**Comment by daviddelucca** [comment]
I would like to contribute but I didn't understand what do you mean by 

> Yes we should change that - the token_type is Bearer. We'll be introducing a new token_use in the introspection response which would then be access token for example. I think we should fix this here!

Will you include the token_use in a newer version and I could just remove that validation?
