### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by andrewbanchich** [ory/oathkeeper#555]
Because Oathkeeper can be used for TLS termination, it would be nice to have it be responsible for enforcing HTTPS by having a rules setting to redirect all HTTP traffic to HTTPS. I think this would be in line with Oathkeeper's design philosophy by not making the upstream APIs have to handle that logic.

**Comment by aeneasr** [comment]
I think Oathkeeper will be taking a direction towards a decision engine (with reverse proxy capabilities as today) but the intent is not to have a replacement for e.g. Nginx or Traefik - so not sure if such a feature would fit that narrowed scope :/
