### ISSUE TITLE
Hydator Mutator Client Credential

### ISSUE THREAD

**Issue by schreddies** [ory/oathkeeper#565]
**Is your feature request related to a problem? Please describe.**

The hydrator have only Basic auth - see config: https://www.ory.sh/oathkeeper/docs/pipeline/mutator/#configuration-4, however for more flexibility, similiar `pre-authorization` mechanism could ba added as in the instropsection authenticator handler: https://www.ory.sh/oathkeeper/docs/pipeline/mutator/#configuration-4

**Describe the solution you'd like**

Adding the whole `pre-authorization` config to the `hydrator` will increase possibilities to use hydrator in multiple cases.

**Describe alternatives you've considered**

Basic auth cannot be used with current config for client credentials for external hydrator service.

**Additional context**

Can contribute to that.

**Comment by aeneasr** [comment]
Hey there, I think this is a good idea! We have a call this week anyways, correct? Let's discuss the ideas there!

**Comment by aeneasr** [comment]
Incorrect stalebot detection - this was assigned a milestone.
