### ISSUE TITLE
homebrew-oauthkeeper seems to be private

### ISSUE THREAD

**Issue by 23doors** [ory/oathkeeper#615]
**Describe the bug**

brew tap ory/oauthkeeper doesn't work as https://github.com/ory/homebrew-oauthkeeper seems to be a private repo.

**Reproducing the bug**

brew tap ory/oauthkeeper

**Expected behavior**

Should work the same as it does for e.g. ory/kratos

**Environment**

MacOS

**Comment by 23doors** [comment]
@zepatrik oh crap, you're right. So I guess it works after all.
`brew tap ory/oathkeeper` works fine

Closing as this was a typo from my side, docs are fine it seems!

**Comment by zepatrik** [comment]
Haha yes, just realized the typo was on your side and not in some script
