### ISSUE TITLE
glob "*" match separator "/"

### ISSUE THREAD

**Issue by ptitpoulpe** [ory/oathkeeper#630]
**Describe the bug**

When using glob in rules matchs, "*" and "**" have the same behavior.

**Reproducing the bug**

Try to match the url "http://localhost:8000/test/test.css" with the match "http://localhost:8000/*.css" (this actually works but must not work)

Seems the use of `glob.Compile` doesn’t have a separator https://github.com/ory/oathkeeper/blob/033f54310864a6cc9894a7970be71a475c18a1e1/rule/engine_glob.go#L103

**Expected behavior**

"*" must not match separator like "/"

**Environment**

- Version: v0.38.4-beta.1
- Environment: Docker

**Comment by aeneasr** [comment]
I see, I think the problem is that we use `.` as separators for domain names, which obviously breaks the `/` separator. But this makes sense to me! PRs welcomed!

**Comment by cameron-martin** [comment]
I've also come across this issue where I get an error about overlapping patterns with the following url patterns:

```
http://example.com/foo/<*>/bar
http://example.com/foo/<*>
```

**Comment by cameron-martin** [comment]
I just submitted a PR for this.
