### ISSUE TITLE
Oathkeeper as relying party in OIDC/Authorization code flow

### ISSUE THREAD

**Issue by synclpz** [ory/oathkeeper#647]
### Use case
As discussed in https://github.com/ory/oathkeeper/discussions/646.

Oathkeeper as an OIDC relying party and cookie-based session  proxy.

I need Oathkeeper to act as an OIDC RP (oauth2 proxy). In this case Oathkeeper stands between my front-end (browser) and back-end (server) and my app uses OIDC from external provider for user authentication.

Oathkeeper needs to be able to: receive auth_code, exchange it for tokens, validate tokens and create cookie-based session for browser, mutating all incoming requests with Authorization and/or other headers using cached tokens before forwarding to back-end.

Sequence is as follows:

1. Browser requests https://myapp/some/path
2. Oathkeeper intercepts request, checks if session cookie is available and valid (it is not)
3. Oathkeeper sets a session cookie and redirects browser to OIDC provider /auth endpoint setting in query all required and configured parameters (client_id, client_secret, scopes, acr_values, etc..) and redirect_uri which is Oathkeeper's endpoint for myapp client_id (initial request is cached in Oathkeeper)
4. OIDC provider performs authentication and consent, then redirects browser to Oathkeeper's endpoint (e.g. https://myapp/oauth2/callback) with auth_code and other required parameters
5. Oathkeeper receives callback with code, exchanges it for tokens, validates and caches tokens, finds out cached initial request by previously issued session cookie, resets session cookie to a new (authenticated) value and redirects browser to initial request
6. Browser performs initial request
7. Oathkeeper checks session cookie, finds cached tokens, validates them if necessary, proxies initial request with configured mutations (e.g. access_token in Authorization header, id_token claims in additional headers and so on).
8. PROFIT

This case is discussed in https://github.com/ory/oathkeeper/discussions/646 and https://ory-community.slack.com/archives/C012RBW0F18/p1614294029035400.

As an alternative one could use https://oauth2-proxy.github.io/oauth2-proxy/ it does implement this scenario but lacks some configuration options available in Oathkeeper (I need to dig deeper though).

**Comment by aeneasr** [comment]
Thank you for raising this issue! This is currently not implemented. We also thought about this in the next iteration of Ory Oathkeeper ( https://github.com/ory/oathkeeper/issues/441 ) but stated this explicitly as a non-goal as there are other projects like Pomerium which have UIs etc included. We're still open to address this but want to keep Ory Oathkeeper free of any UI which might be difficult for this specific use case.

**Comment by synclpz** [comment]
Does this "closed" mean "won't implement"?

**Comment by aeneasr** [comment]
Sorry, forgot the message:

I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️

**Comment by bennesp** [comment]
Given this is the [5th most upvoted issue](https://github.com/ory/oathkeeper/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+), can we discuss re-opening this issue?

To my knowledge, the solution right now, without this feature being built in oathkeeper, requires a custom implementation of the flow, as described by @synclpz, which is often undesirable in the "Don't code. Configure." approach.

This working custom-solution with the home-made implementation of the OIDC relying party is described in this blog post in the `Auth service` section: https://blog.commit.dev/articles/open-source-sundays-building-a-user-management-solution-using-ory-oathkeeper-and-auth0

It is nothing but a server that:
1. Initialize the OIDC flow with a redirect
2. Exchange the code with a token
3. Store the token in a cookie

I understand that the difficulty here doesn't rely on the feature per se but in fitting this feature in the already existing ones of `ory/oathkeeper`, but I was wondering if keeping this issue open could lead to more potential contributors seeing this and to a more open discussion.
