### ISSUE TITLE
wrong format in JWT token

### ISSUE THREAD

**Issue by cezarywysocki** [ory/oathkeeper#654]
**Describe the bug**

Wrong format when fields paste by `id_token` mutator.

**Reproducing the bug**

_Server logs_

_Server configuration_

**Expected behavior**

in JWT token generated by oathkeepr fields `aud` and `scp` should be formatted as below:
```
  "aud": "[
      "app1",
      "app2"
   ]",
  "scope": "[
      "id1",
      "id2",
      "id3",
      "id_added_by_hydrator"
   ]",
```

but instead these fields are formated like this (without `"` and `,`):
```
  "aud": "[app1 app2]",
  "scope": "[id1 id2 id3 id_added_by_hydrator]",
```

**Environment**

- Version: oathkeeper  v0.38.6-beta.1
- Environment: Docker

**Comment by cezarywysocki** [comment]
more details in this thread: https://github.com/ory/oathkeeper/discussions/652

**Comment by aeneasr** [comment]
From your discussion I can see that you are using `{{ print .Extra.aud }}` which is the equivalent of `fmt.Sprintf("%v", []string{"foo", "bar"}` which results in `[foo bar]`. What you probably want is something like `fmt.Sprintf("%s", strings.Join([]string{"foo","bar"}, ","))`. I don't know how this works with go templates right now but I think we have some guidance on that in our docs or at least a link to the template support functions we have.

All of this will hopefully get much easier once we have Jsonnet support implemented instead of Go Templates...

**Comment by terrancesnyder** [comment]
FYI I got this to work using the existing go templates using this;

```
        { 
          "aud": [ "https://my-backend-service/some/endpoint" ],
          "client_id": "{{ print .Extra.client_id }}",
          "scope": "{{ print .Extra.scope }}",
          "roles": {{ print .Extra.roles }},
          "permissions": [{{- range $index, $val := .Extra.permissions -}} {{ if $index }}, {{ end }}"{{ $val }}"{{- end -}}],
          "org_id": "{{ print .Extra.org_id }}",
          "identity": {
            "email": "{{ print .Extra.email }}",
            "family_name": "{{ print .Extra.family_name }}",
            "given_name": "{{ print .Extra.given_name }}",
            "locale": "{{ print .Extra.locale }}",
            "picture": "{{ print .Extra.picture }}"
          }
        }
```

This correctly output the JSON 

```
{
  "aud": [
    "https://my-backend-service/some/endpoint"
  ],
  "client_id": "2c429e39-fa40-4407-81ee-f02f8f48b182",
  "exp": 1717736331,
  "iat": 1717736271,
  "identity": {
    "email": "terrance.a.snyder@gmail.com",
    "family_name": "Snyder",
    "given_name": "Terrance",
    "locale": "",
    "picture": "https://cdn.dev.klustr.io/klustr/1fdb78d4d7f6314e902cf968ea2fb206.jpeg"
  },
  "iss": "https://hydra.dev.klustr.io",
  "jti": "5039856d-e39c-4982-8b80-ee352128db82",
  "nbf": 1717736271,
  "org_id": "klustr.io",
  "permissions": [
    "persons.delete",
    "api.catalogs.create",
    "projects.verification.list", ... etc
<snipped>
```
