### ISSUE TITLE
Additional log information for denied requests(JWT auth)

### ISSUE THREAD

**Issue by eroznik** [ory/oathkeeper#668]
**Is your feature request related to a problem? Please describe.**
When a company offers an authorized public API, information about which user is getting forbidden and/or invalid requests comes in very handy for various support issues.

**Describe the solution you'd like**
Append a configurable "identifier" to error logs outputted after JWT verification(from `pipeline/authn/authenticator_jwt.go` L98 on).

The suggested approach is to have a new configuration value within `AuthenticatorOAuth2JWTConfiguration` which would tell Oathkeeper to extract the value from "Claims"(similar to what `credentials/verifier_default.go` does for validation purposes) and log the "identifier key".
As an example, the JWT verifier could be configured to extract the key "email" from the decoded JWT and log the email as part of the log entry - the company would then be able to assist the client and verify their access configuration(the configuration on the JWT issuer).

**Describe alternatives you've considered**
Logging could be done one request level before(in our case Ambassador API gateway), but Oathkeeper seems a better location for such logs since the authorization happens within Oathkeeper.

**Additional context**
If the feature is interesting and the maintainers approve it for the inclusion, let me know and I'll prepare a PR.

**Comment by eroznik** [comment]
I did a another investigation round and it seems that the way to go(at least for the first phase of improvement), would be to set the `AuthenticationSession.subject` even if the auth validation fails - if it is possible to extract the data from the JWT. In the case of `authenticator_jwt` this means that `subject` would have to be set even if JWT validation fails, before returning the error on line 99.

**Comment by aeneasr** [comment]
Thank you, I think another alternative is to dump the session struct itself which would, if you use e.g. the JSON Formatter, just output it as JSON. That would I assume resolve what you want and be more generic without additional configs?

**Comment by eroznik** [comment]
Yes, that would solve the problem. But the issue is still that the actual session data gets set only and if only the JWT validation passes(issuers, required scope,...), so we'd still have to "extract" the data from the JWT - then we can just dump the whole struct if that's acceptable.
To waste less space in logs we should also probably consider the approach Oathkeeper uses for various mutations, e.g. use the Go `text/template` package to extract data from a struct(sesston struct) and print just what you want(as you already mention, the downside of this is an additional config).

**Comment by aeneasr** [comment]
I'm not sure if making the logging configurable is the best of approaches here - it's error prone, special knowledge, and hard to replicate. If the payload validation is the problem, we can simply add one or two log statements there?

**Comment by eroznik** [comment]
I wouldn't say that the payment validation is an issue, JWT validation failure is totally acceptable(e.g. a user hasn't got the required scope).
The RC for the feature requests is exactly this example, i'd like to the "AuthenticationSession.subject" also in cases when JWT validation fails(for any reason.
Would it be ok if i change the implementation as such:
- validate the JWT(as it is of now)
- if the decode with validations results in an error, a second decode of the the JWT is performed, this time without "strict validations" so "subject" can be still extracted from the claims.
- the extracted "subject" is set to the session, the session data gets logged similar to now in the "request_handler" through "logger.withFields"

**Comment by aeneasr** [comment]
> if the decode with validations results in an error, a second decode of the the JWT is performed, this time without "strict validations" so "subject" can be still extracted from the claims.
>the extracted "subject" is set to the session, the session data gets logged similar to now in the "request_handler" through "logger.withFields"

I don't think this is a good idea as it would incorrectly set the session. This can lead to issues down the road - I would instead handle this in the JWT handler itself for debugging. Another alternative is to just use something like OpenTracing spans which is probably the correct aproach for debugging this anyways!

**Comment by eroznik** [comment]
Ok, this makes totally sense. Didn't think it through, for sure it could cause issues down the chain. Since you mention OpenTracing spans, is it still acceptable that we proceed with this improvement(at least to add additional log info in the JWT authenticator)?
