### ISSUE TITLE
Allow falling back to anonymous authenticator when previous authenticator matches but fails.

### ISSUE THREAD

**Issue by cameron-martin** [ory/oathkeeper#682]
**Is your feature request related to a problem? Please describe.**

I have some endpoints that are accessible to anyone, but the API server is still interested to know who the user is if they are authenticated. These routes have two authenticators defined, `cookie_session` and `anonymous`, the intention being that the `anonymous` one is fallen back on if the `cookie_session` one fails. However, if a session is present but has expired then oathkeeper returns a 401 and does not fall back to the anonymous authenticator. According to [the documentation](https://www.ory.sh/oathkeeper/docs/pipeline/authn) this is intentional:

> If handler `a` is able to handle the provided credentials, then handler `b` and `c` will be ignored.

**Describe the solution you'd like**

Possibly there could be an extra option in the authenticator configuration in the access rules to allow falling through to the next authenticator upon failure.

**Describe alternatives you've considered**

The default could be to fall through to the next authenticator upon failure, but I'm sure there is a good reason why this is not done.

**Additional context**

None

**Comment by aeneasr** [comment]
This is tricky as misconfiguration - or assuming fallthrough per default - will lead to security issues as you can now access stuff without any credentials. The default should always be: "you are not allowed to do this" - so explicitly allowing stuff.

I understand the use case though, not sure how to implement it best however. Maybe something with error handling?

**Comment by cameron-martin** [comment]
> This is tricky as misconfiguration - or assuming fallthrough per default - will lead to security issues as you can now access stuff without any credentials.

How does it make it less secure than currently? If I'm understanding correctly you would only be able to access stuff without any credentials if the anonymous authenticator was enabled in an access rule. This allows the same level of access as can be gained now because the user can currently create a request that is ignored by previous authenticators even without falling through on errors, for example by not supplying a session cookie & Authorization header.

**Comment by cameron-martin** [comment]
Potentially relates to https://github.com/ory/oathkeeper/issues/441#issuecomment-652587583

**Comment by PeteMac88** [comment]
I also think an option to evaluate the next authenticator instead of failing the request is also interesting to support multi-tenancy regarding the auth server. In case I want to secure the same route with two different auth servers via `oauth2_introspection` this is not possible because the depending on the access tokens one of the introspection requests would fail.

**Comment by Serhii-the-Dev** [comment]
There should be some methods to resolve this issue. We are currently migrating from a homemade JWT-based authorization on static token to Hydra using the client credentials flow and we obviously need to add the `oauth2_introspection` authenticator...which immediately breaks our current `bearer_token` authenticator if placed on top and vice versa. So far we simply put the new version under a specific URL prefix however I'm not sure it's the best solution that will work for everyone.

**Comment by renom** [comment]
Btw, how kratos api endpoints solves this? Does it work the same way as in oathkeeper?
For example: call some endpoint with incorrect token in a cookie, but with a valid token in a header. Will it return an error?

**Comment by safizn** [comment]
What is the current approach to implement invalid cookie session passthrough?
