### ISSUE TITLE
provide "debug" level feedback on template execution output

### ISSUE THREAD

**Issue by stensonb** [ory/oathkeeper#698]
When using templating, malformed syntax can be difficult to debug.  An executed template resulting in invalid json fails the json parser with cryptic results.

For example, when attempting to use the sprig integration to copy all claims from a `jwt` authenticator to an `id_token` mutator, I tried this:

```
  mutators:
    - handler: id_token
      config:
        claims:
          '{"aud": ["https://example.com"], "ci_job_jwt": "{{ toRawJson .Extra }}"}'
        ...
```

which resulted in the following excerpt from the `oathkeeper serve` logs:
```
{
...
  "error":{"message":"invalid character 'e' after object key:value pair",
    "trace":"...",
    ...
  }
}
```

I'd like `debug` level logging to output the result of the executed template, so that I may decipher where my syntax error is (in my example above, I don't need to encapsulate the `{{ toRawJson .Extra }}` template variable in quotes -- this would been relatively easy to see if I could view the resulting template output).

I believe one way to solve this is to:
1. add a `logger` instance to each mutator
2. call `logger.Debugf("Template results: %s", b.String())` before attempting to pass the template results to the json parser.  In my example, I'd add this line here: https://github.com/ory/oathkeeper/blob/master/pipeline/mutate/mutator_id_token.go#L169

I do think this is a common enough problem (debugging template output) that solving this in _each_ mutator is redundant.  But, I could use some direction on how to generalize this solution.

I do see the https://github.com/ory/oathkeeper/blob/master/pipeline/mutate/mutator_hydrator.go#L98 has a logger object.  I wonder if this approach should be applied to all mutators.

**Comment by stensonb** [comment]
whatever does get logged should pass through the `leak_sensitive_values` boolean logic...

**Comment by aeneasr** [comment]
Yeah, absolutely agree. Would definitely appreciate a PR. We could send this stuff to OpenTracing for even better debugability - but I think having it in the logs is more developer friendly in the beginning / dev phase.
