### ISSUE TITLE
cmd: Should not fatal if ORY Hydra SDK is unable to start

### ISSUE THREAD

**Issue by arekkas** [ory/oathkeeper#71]
See https://community.ory.sh/t/please-specify-the-ory-hydra-endpoint-url/491

**Comment by Detrous** [comment]
Update --help command. I need to specify this for work:
CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_URL=hydra_url

But this env variable not described in help

**Comment by arekkas** [comment]
Yes, seems like it isn't being updated. I think one possibility is to introduce an `CREDENTIALS_ISSUER_ID_TOKEN_STRATEGY` which can be set to `hydra` or `hs` (for hmac-sha). The second would be the default and we could require the user to set a password and (optionally) generate a random one.

That way there would no longer be a direct dependency to ORY Hydra and thus the tutorial would work and ORY Oathkeeper would be standalone.

I'll work on this tomorrow.

**Comment by gentunian** [comment]
I will leave this for reference and shortcut for people having the same issue. For more information read the [oathkeeper upgrade guide](https://github.com/ory/oathkeeper/blob/master/UPGRADE.md)

I was having the same issue with the `examples/full-stack` commit 76bd4877044c5bdded0f6b8b8ad12cd5c7f087af (seems outdated as this is the last commit from examples) and environment has `CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_URL` set that should be changed to: `CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_ADMIN_URL`

Working environment:
```
    environment:
      - LOG_LEVEL=debug
      - PORT=4456
      - DATABASE_URL=postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
      - ISSUER_URL=http://localhost:4455/
      - AUTHORIZER_KETO_WARDEN_KETO_URL=http://keto:4466
      - CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM=ory-hydra
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_JWK_SET_ID=resources:hydra:jwk:oathkeeper
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_ADMIN_URL=http://hydra:4445
```

**Comment by aeneasr** [comment]
Thanks! Master is not yet released but with rc.1 the examples will be upgraded too!
