### ISSUE TITLE
Setting header in the response to the list of possible actions for the subject

### ISSUE THREAD

**Issue by mitar** [ory/oathkeeper#729]
**Is your feature request related to a problem? Please describe.**

I am just learning about Oathkeeper and Keto, so maybe I am missing something obvious or maybe this is far out of scope.

I have an API an server which provides some actions (e.g., `read`, `setOwner`, `updateBody`) over some resources (e.g., `blogPost`, `comment`). I am trying to understand how I could use Oathkeeper and Keto to have a centralized decision making for all API requests to decide if the API request should be allowed of not. While Oathkeeper and Keto solves the problem on the server side, I would also want to solve it for the frontend: imagine in the UI shown to the user that there are buttons/forms to "set owner" or "update body". So those buttons/forms should be shown only if the subject has permissions to do those actions. So the question is how to get this information to the frontend from Keto through Oathkeeper.

**Describe the solution you'd like**

I think that the best solution would be that Oathkeeper keeper adds a HTTP header to the response going to the client (i.e., frontend) which are allowed for the current subject on the same resource. So I do `read` API request to `blogPost/1`, then in the response I should see something like `X-Allowed-Actions: read, updateBody` because this subject can do `read` and `updateBody` actions on this resource, but not `setOwner`. This would allow the client/frontend to know which buttons/forms to show, or in general, which other API calls can call.

**Describe alternatives you've considered**

I could access this information by making a special API request to Keto through some dedicated API service. But I think having that all done in one point, which is already talking to Keto to validate the API request is a better way.

**Comment by aeneasr** [comment]
This should be possible already using rhe header mutator!

**Comment by mitar** [comment]
My understanding is that mutators modify **request** headers and I am asking here for modifying **response** headers which would then be send back to the client/browser?

**Comment by aeneasr** [comment]
Mutators modify request headers to the upstream. Mutation of response headers is currently expected to happen in the upstream.

**Comment by mitar** [comment]
Ehm, but the upstream does not have necessary information: which methods/API endpoints can the caller call. The upstream has no authentication and just trusts oathkeeper. So the oauthkeeper is the only one which has this information.

It is true that I could configure oathkeeper to pass this information to the upstream using a request header and then upstream would copy it to the response, but I find this ugly and it means that the upstream has to be modified to do so (or have another proxy in between). But even that I do not think it is really possible, I do not see a way to get necessary information into `AuthenticationSession` from Keto, for example.

**Comment by aeneasr** [comment]
Zero-trust modelling would expect the upstream to verify the credentials sent to it in some way. For example, using the "id_token" mutator the upstream would decode the JWT and verify it's signature with Ory Oathkeeper to ensure that the caller is actually someone that has been authenticated. The methodology used here of course depends on your security and trust model. If you trust that no-one will ever have direct access to the upstream without Ory Oathkeeper, you may not want to check that. However, in distributed systems, this trust is usually not there.

What's the use case you're looking at?

**Comment by mitar** [comment]
I decided not to use oathkeeper because of this limitation, so issue can be closed.
