### ISSUE TITLE
Deletion of conflicting rule doesn't solve the route conflict

### ISSUE THREAD

**Issue by oscartrullols** [ory/oathkeeper#73]
I have created some oathkeeper rules, adding them as it's done in "ory/examples".

by mistake, two of them were applying to the same route, so obviously, the error when trying to access the route was:
`{"error":{"code":500,"status":"Internal Server Error","message":"Expected exactly one rule but found multiple rules"}}`

I delete one of them (and verify it has been deleted with GET /rules), but the error doesn't go away, even after waiting for more than 30s

see [gist](https://gist.github.com/oscartrullols/04f486a223daee55fd5719291b0e9f83) for details and steps to reproduce the problem

**Comment by arekkas** [comment]
I can reproduce this.
