### ISSUE TITLE
.MatchContext.Header cannot be evaluated

### ISSUE THREAD

**Issue by janiskemper** [ory/oathkeeper#737]
**Describe the bug**

Using .MatchContext.Header as suggested in the [docs](https://www.ory.sh/oathkeeper/docs/next/pipeline/#session) leads to the error 
```
{"error":{"code":500,"status":"Internal Server Error","message":"template: 3aced85822722c7de82d3788d8f9d90902c3a9de3459d5502a6a75b222c78125:2:35: executing \"3aced85822722c7de82d3788d8f9d90902c3a9de3459d5502a6a75b222c78125\" at \u003c.MatchContext.Header.Get\u003e: can't evaluate field Header in type authn.MatchContext"}}
```
if used in the remote_json authorizer. The following better formatted error comes if it is used in the header mutator: 
```
{"error":{"code":500,"status":"Internal Server Error","message":"error executing headers template \"{{ .MatchContext.Header.Get \"some_header\" }}\" in rule \"test\": template: test:x-user:1:16: executing \"test:x-user\" at \u003c.MatchContext.Header.Get\u003e: can't evaluate field Header in type authn.MatchContext"}}
```

**Reproducing the bug**

Clone Ory Kratos (e.g. v0.6.3-alpha.1) and run 
```
docker-compose -f quickstart.yml -f quickstart-oathkeeper.yml up --build --force-recreate
```
Update the Oathkeeper settings so that the header mutator is included with a config similar to the following:
```
  remote_json:
    enabled: true
    config:
      remote: http://endpoint:1234/check
      payload: |
        {
          "config_field": "{{ .MatchContext.Header.Get "some_header" }}" 
        }
```
and use this mutator for one of the access rules of the Kratos UI node.

**Expected behavior**

I expect this to give me the value of the respective header with key "some_header" - not to throw an error.

**Environment**
I used the following images (these are the defaults for the quickstart):
- oryd/oathkeeper:v0.38
- oryd/kratos:v0.6.3-alpha.1-sqlite

**Comment by aeneasr** [comment]
That change is not released - you're browsing the "next" docs meaning current master. To view the documentation for the version you're using select the version from the docs in the top left corner! :)

**Comment by janiskemper** [comment]
@aeneasr Thanks for clarification. What I didn't understand from the docs is whether there is a way of analyzing the header property of AuthenticationSession struct or not. I'm confident there is, otherwise the struct wouldn't have the header in the first place (I guess), but I have no idea how. Can you help me out on this?

**Comment by janiskemper** [comment]
@aeneasr in the latest docs you have this example again (v0.38). Is this now working?

**Comment by aeneasr** [comment]
Which version of v0.38 are you using?

**Comment by janiskemper** [comment]
v0.38.15-beta.1

**Comment by aeneasr** [comment]
Ok, thank you - reopening. Could be a bug, would you be up to investigate this? Sorry for closing this initially, I don't quite remember but I thought a PR was merged but not yet released. :)

**Comment by janiskemper** [comment]
Sorry, I didn't want to say that it is NOT working. I just wanted to ASK whether it is. I didn't see anything related to this in the release notes.

**Comment by aeneasr** [comment]
From the looks of it, it *should* be working :D

**Comment by janiskemper** [comment]
Thanks! I can confirm :D I started testing as I realized that you expect this to work - and it does! This is really helpful, thanks to the Ory team :)
