### ISSUE TITLE
id_token mutator: broadcasts of private: (public part) keys at `.well-known/jwks.json`

### ISSUE THREAD

**Issue by akornatskyy** [ory/oathkeeper#741]
Scenario:
- Hydra RSA keys are available at http://localhost:4445/keys/test2
- Oathkeeper uses `id_token` mutator, `jwks_url` is pointing to above
- JWT token is issued correctly, `kid` has prefix `public:`
- Oauthkeeper broadcasts both `public:` and `private:` (public part) keys at `.well-known/jwks.json`.

It doesn't make sense to broadcast `private:` (public part) since JWT uses `public:` for `kid`.

**Comment by aeneasr** [comment]
Thank you!

This is basically an issue in Ory Hydra which currently separates public/private keys using these prefixes. There's an open PR for that https://github.com/ory/hydra/pull/2459/files which is unfortunately currently stale.

So I would mark this as a duplicate of the linked hydra issue as for Ory Oathkeeper, the two keys are basically separate keys and it shouldn't try to interpret the kid.

So I will be closing as a dupe, but feel free to continue to comment / share ideas!
