### ISSUE TITLE
Add passthrough support for request headers in http requests from Oathkeeper.

### ISSUE THREAD

**Issue by mugioka** [ory/oathkeeper#752]
**Is your feature request related to a problem? Please describe.**
I would like to be able to pass the x-request-id in the client request header for all HTTP requests from Oathkeeper (e.g. [here](https://github.com/ory/oathkeeper/blob/master/pipeline/authn/authenticator_oauth2_introspection.go#L186)).
This is because when using [Jaeger](https://www.jaegertracing.io/docs/1.23/), we can use x-request-id to aggregate spans and consider them as part of the same request.

**Describe the solution you'd like**

What I'm thinking is to have a wrapped method to create an HTTP client and pass the client request as an argument to it.

e.g
```
# The headers is assumed to be the key of the header you want to pass through from the oathkeeper configuration file.

func NewRequestPassThrogh(method, path url, body io.Reader, clientRequest *http.Request, headers []string) (*http.Request, error) {
    req, err := http.NewRequest(method, path, body)
    if err != nil {
        return nil, err
    }
   for i ,v := range headers {
       req.Header.Set(v, clientRequest.Header.Get(v))
    }
    
    return req, nil
}
```

**Comment by aeneasr** [comment]
This really sounds like a useful thing to have. There's a PR going on for adding self-signed CAs to all upstream requests (#744) so we could probably re-use the ideas introduced there to this PR. Would you be open to work on a PR for this? :)

**Comment by mugioka** [comment]
Thanks for the reply.

OK, Once https://github.com/ory/oathkeeper/pull/744 is merged, I'll open the PR for this issue.
