### ISSUE TITLE
Retry bug-fix in ory/x/httpx not adopted in oathkeeper

### ISSUE THREAD

**Issue by DimitarPetrov** [ory/oathkeeper#765]
**Describe the bug**

It looks like there was a bug in `ory/x/httpx` library regarding the retry logic. Reference PR: https://github.com/ory/x/pull/300

It looks like the fix is not adopted in oathkeeper. I verified with the new `NewResilientClient` and the issue is no longer reproducible.

**Reproducing the bug**

A server returning 5XX status code used in a hydrator mutator will result in the following log entries when trying to retry:

```
time="2021-06-28T08:59:36Z" level=warning msg="The mutation handler encountered an error" error="Post \"http://compass-director.compass-system.svc.cluster.local:8080/v1/tokens/resolve\": http: ContentLength=274 with Body length 0" granted=false http_host=compass-gateway.kyma.local http_method=GET http_url="http://compass-gateway.kyma.local/connector/graphql" http_user_agent=curl/7.64.1 mutation_handler=hydrator reason_id=mutation_handler_error rule_id=compass-connector-one-time-tokens.compass-system subject=
```

**Comment by aeneasr** [comment]
Yes, that is correct. The problem is that we need to upgrade ory/x which incurrs several breaking changes on the config system and requires some refactoring of Ory Oathkeeper :/
