### ISSUE TITLE
Important notice: project renaming

### ISSUE THREAD

**Issue by aeneasr** [ory/oathkeeper#804]
Please see: https://github.com/ory/oathkeeper/blob/master/README.md#project-renaming

**Comment by Arcanorum** [comment]
What about when some other extremist group names themselves whatever the new name ends up being?
I could probably count all of the people that actually care about the current name on 0 hands, but 🤷‍♀️.

**Comment by schreddies** [comment]
That's shame! `Oathkeeper` was such a nice name!

**Comment by stuartpb** [comment]
What are your thoughts on what the project's new name would be? I think "[Needle][1]" would make sense (as a proxy you pass through like the eye of a needle). It also makes me think of a solution that's *smaller* than most others, rather than one that's "too big for me".

[1]: https://gameofthrones.fandom.com/wiki/Needle

**Comment by aeneasr** [comment]
Thank you for the suggestion! We will add it on the list of idea names :) Not sure how the voting will go though. In general we think going with the ecosystem greek naming thing might be good for consistency. Ory Oathkeeper really is the only project that doesn't follow that convention so far.

**Comment by wesleyfantinel** [comment]
Triton would match with Hydra  😃

**Comment by TarekAS** [comment]
Making it more consistent with the other Greek names is a valid reason. In that case I would suggest [Sancus](https://en.wikipedia.org/wiki/Sancus)

However, the current name is already awesome and well fitting. I immediately thought of the GoT sword when I read it, not whoever those guys are (and now I'll always make that association in my head).

**Comment by bewest** [comment]
`oauthkeeper` - really looking forward to jsonnet support in next-gen. Heracles or Hercules was the gatekeeper if keeping with Greek mythology. `oauthkeepr` if you want to stick with web 2.0, and `oauthkeepd` if you want to stay unix old school.

**Comment by forresthopkinsa** [comment]
A point against the Greek naming: the current name is extremely self-descriptive and marketable, IMO; far more than other Ory projects. Also, it earns a lot of nerd points :)

My two cents: you could maintain the self-descriptiveness aspect, _and_ retain the fantasy vibe, _and_ dramatically reduce confusion after the rename, by going with another famous fictional sword: **Oathbringer**.
