### ISSUE TITLE
Add `/.well-known/openid-configuration` endpoint when using id_token mutation

### ISSUE THREAD

**Issue by lwj5** [ory/oathkeeper#806]
**Is your feature request related to a problem? Please describe.**

The standard JWKS access flow has an endpoint `/.well-known/openid-configuration` to obtain the URL for the JWKS public key. 

The app then accesses that URL to obtain the key and validate the JWT token. 
It would be good practice to follow this standard. This has been coded into a few open-source JWKS middleware, as it is used by major OIDC providers such as Auth0, Okta, Microsoft, Google, etc.

Some examples of `/.well-known/openid-configuration`:
https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
https://developer.okta.com/docs/reference/api/oidc/#response-example-success-8

**Describe the solution you'd like**

Oauthkeeper creates endpoint `/.well-known/openid-configuration` with key `jwks_uri` that points to `/.well-known/jwks.json`

**Describe alternatives you've considered**

Copying source code from open-source middleware projects and put them in your project and making the appropriate changes.

**Additional context**

**Comment by aeneasr** [comment]
Thank you for the idea. However, that endpoint is for OpenID Connect, but Ory Oathkeeper is not an OpenID Connect provider - therefore it does not make sense to have it as Ory Oathkeeper would fake being an OpenID Connect provider.

Ory Hydra supports that endpoint, as it is an OpenID Connect Provider!

**Comment by lwj5** [comment]
Okay, not an issue. I'll just adapt those JWKS middle for this case. Thanks for considering.

**Comment by anderslauri** [comment]
Following up here. I believe a compromise would be great (still following specification), i.e. `Google Workload Identity` with an external IDP configured requires `/.well-known/openid-configuration` as discovery document to retrieve `jwks_uri` attribute.

Proposal. Expose `/.well-known/openid-configuration` with a single attribute which is `jwks_uri`. The alternative is to configure a distinct issuer URL in the id token and implement this endpoint within such an exposed service.
