### ISSUE TITLE
Provide JSON Schema for Access Rules

### ISSUE THREAD

**Issue by tobbbles** [ory/oathkeeper#828]
**Is your feature request related to a problem? Please describe.**

I would like to validate my Access Rules (in JSON) against a schema, firstly in my editor through magic and a `"$schema": "..."` item, and secondly in my CI pipelines through tools such as [ajv-cli](https://www.npmjs.com/package/ajv-cli).

**Describe the solution you'd like**

A published `.schema/rules.schema.json` that defines a [JSON Schema](https://json-schema.org/) for the Access Rules, documented currently [here](https://github.com/ory/oathkeeper/blob/d942c043aa2370b87e0dd822440ad39d809755f9/docs/versioned_docs/version-v0.37/api-access-rules.md#access-rule-format).

**Describe alternatives you've considered**

Not having schemas? This is more so a quality-of-life improvement for end users, and hopefully contributors alike.

**Additional context**

Furthermore more could be added to drive some schema-driven documentation.

The Swapper API Schema already has a section for `rules`, however this isn't a JSON Schema, but provides a good starting point. https://github.com/ory/oathkeeper/blob/d942c043aa2370b87e0dd822440ad39d809755f9/.schema/api.swagger.json#L616

**Comment by aeneasr** [comment]
Sorry for the late reply, that is a great idea! Contribs welcomed :)

**Comment by imrushi** [comment]
Hi, @aeneasr I can take this issue I can work on it. :)
