### ISSUE TITLE
Support gzipped responses in check session URLs

### ISSUE THREAD

**Issue by aeneasr** [ory/oathkeeper#836]
**Describe the bug**

See https://github.com/ory/oathkeeper/pull/835

**Comment by dreverri** [comment]
If a request manually sets the `Accept-Encoding` header the transport will not automatically decode the response.

https://pkg.go.dev/net/http#Transport.DisableCompression

Currently, it looks like oathkeeper copies all the headers from the original request so if the original request has the `Accept-Encoding` header the body will not decompressed.

https://github.com/ory/oathkeeper/blob/9375f92b5d647c8417389158bf66e060b4ab8ad6/pipeline/authn/authenticator_cookie_session.go#L131

**Comment by aeneasr** [comment]
Ah, I see, that makes sense!

**Comment by till** [comment]
@aeneasr PR coming soon. We somehow hit that.
