### ISSUE TITLE
`Oathkeeper` does not respect `TRACING_PROVIDER=otel`

### ISSUE THREAD

**Issue by mdreizin** [ory/oathkeeper#888]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

`Oathkeeper` does not respect `TRACING_PROVIDER=otel` to use OpenTelemetry.

### Reproducing the bug

`docker run ... -e TRACING_PROVIDER=otel ...`

### Relevant log output

```shell
time=2021-12-28T23:25:00Z level=fatal msg=Unable to initialize Tracer. audience=application error=map[message:unknown tracer: otel] service_name=ORY Oathkeeper service_version=v0.38.15-beta.1
```

### Version

v0.38.15-beta.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

### Additional Context

It would be nice to update [`ory/x`](https://github.com/ory/x) to the latest version to use [`otel`](https://github.com/ory/x/blob/master/tracing/tracer.go#L175) tracing provider.

**Comment by aeneasr** [comment]
We will need to upgrade ory/x! However, one problem is that ory/x has developed quite a lot since we included it here and we did not yet have the time to update ory oathkeeper's config system to the new ory/x config system. So upgrading will not be as easy as just bumping the go mod version :(

**Comment by mdreizin** [comment]
@aeneasr thank you very much for sharing that! I hope you will be able to migrate to use the latest version in the further ;)

**Comment by ouranders** [comment]
It would be great to use otel, any updates on this issue @aeneasr?

**Comment by bodymindarts** [comment]
We want to bring in oath keeper as a hard dependency in our stack but this is somewhat of a blocker.

**Comment by ldb** [comment]
Same here, we use OpenTelemetry for all of our tracing, not having this in Oathkeeper but [in Hydra](https://github.com/ory/hydra/issues/2597) is a blocker for us.

**Comment by edude03** [comment]
Still true in the latest release fwiw

```
docker run -e TRACING_PROVIDER=otel -ti oryd/oathkeeper serve
Thank you for using ORY Oathkeeper v0.40.0!

Take security seriously and subscribe to the ORY Security Newsletter. Stay on top of new patches and security insights.                                 

>> Subscribe now: http://eepurl.com/di390P <<

The configuration contains values or keys which are invalid:
tracing.provider: otel
                  ^-- value must be one of "zipkin", "jaeger", "datadog", "elastic-apm"

FATA[2022-11-17T18:09:25Z] Failed to initialize configuration            audience=application error=map[message:I[#/tracing/provider] S[#/properties/tracing/properties/provider/enum] value must be one of "zipkin", "jaeger", "datadog", "elastic-apm"] service_name=ORY Oathkeeper service_version=v0.40.0
```
