### ISSUE TITLE
Allow more time.Duration-esque timeout configurations

### ISSUE THREAD

**Issue by lucatonile** [ory/oathkeeper#908]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Tried to set proxy idle timeout to `10m20s` but got `does not match pattern "^[0-9]+(ns|us|ms|s|m|h)$"`. Thought it would work since Oathkeeper is written in Go.

The schema validation as per: https://github.com/ory/oathkeeper/blob/69c64e79eb7eb5ad415503c8f71a424f8da90f10/.schema/config.schema.json#L41 is a bit misleading since Oathkeeper actually uses `time.ParseDuration()` :https://github.com/ory/oathkeeper/blob/d942c043aa2370b87e0dd822440ad39d809755f9/driver/configuration/provider_viper.go#L169

### Describe your ideal solution

Can only come up with updating regexps in https://github.com/ory/oathkeeper/blob/master/.schema/config.schema.json

### Workarounds or alternatives

Update regexps https://github.com/ory/oathkeeper/blob/master/.schema/config.schema.json

### Version

v0.38.12-beta.1

**Comment by aeneasr** [comment]
Hey, this totally makes sense, the correct regexp is:

```
"^([0-9]+(ns|us|ms|s|m|h))+$", 
```

**Comment by lucatonile** [comment]
That will match on e.g. "20s20s" too, no? 🤔 I'm not that experienced in regex and making a time.Duration format matcher in pure regex seems like quite a feat, but I could try to throw something together when Im at the computer. 

Haven't gone through the repo very thorougly but I wonder if it would be better to do the validation in Go instead

**Comment by aeneasr** [comment]
That's true. The validation happens in Go anyways, this is just like a first line of defense against any typos people might make :)
