### ISSUE TITLE
Invalid Url Validator

### ISSUE THREAD

**Issue by kucjac** [ory/oathkeeper#92]
Hello I'm using your full-stack within my app.

I have a problem with patching the url matcher. When i try to add `<http|https>` regexp just as you shown within the guide, the API replies with: 

> Value \"<http|https>://hydra.myurl.com/keys\" from match.url field is not a valid url.

It is probably the problem with putting raw value into [govalidator](https://github.com/asaskevich/govalidator).

**Comment by arekkas** [comment]
Yeah, that looks like a bug!
