### ISSUE TITLE
Can CORS settings be configured/extended per rule?

### ISSUE THREAD

**Issue by dan2kx** [ory/oathkeeper#926]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I would like to configure cors settings on a rule by rule basis

### Describe your ideal solution

I'm using oathkeeper-maestor in a kubernetes environment to create my rules and it would be useful to be able to adjust the cors settings such as allowed origins or exposed headers per rule rather than for the whole service.

### Workarounds or alternatives

I'm not sure if this is currently possible, i couldn't find anything in the docs

### Version

v0.38.15

**Comment by a-manraj-pvotal** [comment]
I would expect to have your CORS rules in your north south microservice gateway (emissary, ambassador, traefik, contour, kong) mapping.

**Comment by aeneasr** [comment]
I agree, this is out of scope for Ory Oathkeeper - sorry :/
