### ISSUE TITLE
Support working with query string and JSON body

### ISSUE THREAD

**Issue by renom** [ory/oathkeeper#964]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Support working with query string and JSON body

### Describe your ideal solution

1. Mutating and hydrating query string and JSON body (e.g. adding/replacing/removing a query string parameter or a JSON body path)
2. Extracting data from query string and JSON body for keto_engine_acp_ory (e.g. data from a query string parameter or a JSON body path)
3. Support autherizer rules for query string parameters and JSON body paths (e.g. allowing or disallowing specific values)

### Workarounds or alternatives

-

### Version

-

**Comment by omerlh** [comment]
Any updates on that? It seems like #843 is related to this. 
We are more interesting in query params right now, will a PR will be accepted here?

**Comment by omerlh** [comment]
I found a workaround for query params: 
```
{{ .MatchContext.URL.Query.Get \"a\" }}
```

No code change is requires in oathkeeper to support it, just the power of Go templates 💪

**Comment by ViswanathB** [comment]
> I found a workaround for query params:
> 
> ```
> {{ .MatchContext.URL.Query.Get \"a\" }}
> ```
> 
> No code change is requires in oathkeeper to support it, just the power of Go templates muscle

Like this idea: @omerlh Did you find any issues with this at scale?

**Comment by omerlh** [comment]
Nope, this working pretty well for us

**Comment by denysandriyanov** [comment]
Have you had a chance to get the way how to extract some values from original request body?

**Comment by omerlh** [comment]
If you use the [`remote`](https://www.ory.sh/docs/oathkeeper/pipeline/authz#remote) authorizer the full request body is sent to this service so you can use the request body for authZ. We built a small service that handle authZ so it also handles this part.
