### ISSUE TITLE
Add additional headers for `remote_json` authorizer

### ISSUE THREAD

**Issue by gen1us2k** [ory/oathkeeper#969]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Since Ory Keto is an Ory Network citizen right now and requires for additional token set to the `Authorization` Header, it makes it impossible to configure the `remote_json` authorizer against Ory Cloud Keto.

### Describe your ideal solution

It would be best to have `headers` or something similar compared to `remote` authorizer to configure oathkeeper `remote_json` authorizer

### Workarounds or alternatives

It's possible to create a simple HTTP service that proxies requests and adds `Authorization` header

### Version

latest

**Comment by omerlh** [comment]
+1 having the same challenge, trying to integrate oathkeeper with [OpenFGA](https://auth0.com/developers/lab/fine-grained-authorization)

**Comment by martinhale** [comment]
+1 to this!
