### ISSUE TITLE
Add OPA authorizer

### ISSUE THREAD

**Issue by aeneasr** [ory/oathkeeper#98]
https://github.com/open-policy-agent/opa

**Comment by aeneasr** [comment]
It's not clear how to work with OPA's unstructured data approach. I'm closing this until there is clarification. Feel free to discuss this though.

**Comment by tloriato** [comment]
How did this progress?

**Comment by zepatrik** [comment]
Keto as a separate project was started. We are currently in the process of rewriting it from the ground up, a lot of exciting stuff happening there :wink: OPA integration will be possible there still, see https://github.com/ory/keto/issues/318
